### Libraries

In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

### Data

In [ ]:
path = '/content/drive/MyDrive/Colab/Files/PROJECT/PROJETOFINAL_hoteis.csv'
data = pd.read_csv(path)

### Opçoes

In [ ]:
pd.set_option('display.max_columns', None)

### Limpeza

In [ ]:
data

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes.main.latitude,geocodes.main.longitude,geocodes.roof.latitude,geocodes.roof.longitude,location.address,location.country,location.cross_street,location.formatted_address,location.locality,location.postcode,location.region,related_places.children,location.address_extended,related_places.parent.fsq_id,related_places.parent.name,location.neighborhood,popularity,rating,tastes,tips,verified,website,hours.display,hours.is_local_holiday,hours.open_now,hours.regular,hours.seasonal,social_media.facebook_id,social_media.twitter,description,social_media.instagram,price
0,0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),Asia/Tokyo,35.697955,139.770792,35.697955,139.770792,外神田1丁目2-12,JP,NaN,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,[],NaN,NaN,NaN,NaN,0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't...",False,https://www.anshin-oyado.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...","[{'closed': True, 'hours': [{'close': '+0000',...",5.511922e+14,NaN,NaN,NaN,NaN
1,1,517089e9e4b0d21e986153c3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2776,/v3/places/517089e9e4b0d21e986153c3,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,Asia/Tokyo,35.679886,139.737048,35.679886,139.737048,紀尾井町1-2,JP,NaN,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo,"[{'fsq_id': '57a6b47e498ed8c9b2ac1db1', 'name'...",ザ プリンスギャラリー東京紀尾井町 34F,552f81cc498ed8c8eab7eb25,フレッシュネスバーガー東京ガーデンテラス紀尾井町,NaN,0.997768,9.0,"['friendly staff', 'scenic views', 'hotel', 'b...","[{'created_at': '2019-03-03T02:13:09.000Z', 't...",True,https://www.princehotels.co.jp/kioicho/,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],7.888628e+14,NaN,"The Prince Gallery Tokyo Kioicho, a Luxury Col...",princegallerytokyokioicho,NaN
2,2,4f80f0bae4b0e160b9c9e122,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2480,/v3/places/4f80f0bae4b0e160b9c9e122,Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧),Asia/Tokyo,35.712912,139.777796,35.712912,139.777796,上野7丁目2-16,JP,NaN,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo,NaN,NaN,NaN,NaN,NaN,0.991224,8.7,"['saunas', 'open-air bath', 'cold-water bath']","[{'created_at': '2021-12-06T00:50:18.000Z', 't...",False,http://www.saunahokuou.com,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,hokuo8000,NaN,sauna.capsule.hokuo,NaN
3,3,598970be35f9830771f06b3f,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],3106,/v3/places/598970be35f9830771f06b3f,APA Hotel Asakusa Tawaramachi-Ekimae (アパホテル 浅草...,Asia/Tokyo,35.710112,139.790113,35.710112,139.790113,西浅草1丁目2-3,JP,NaN,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo,"[{'fsq_id': '598c3750fdb9a7339cad21c7', 'name'...",NaN,NaN,NaN,['浅草'],0.993129,8.7,NaN,"[{'created_at': '2020-02-11T07:46:18.000Z', 't...",False,https://www.apahotel.com/hotel/shutoken/asakus...,NaN,False,False,NaN,[],9.189654e+14,_apahotel,NaN,apahotel_official,NaN
4,4,5211312e11d259e1a2b3385a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],1969,/v3/places/5211312e11d259e1a2b3385a,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,Asia/Tokyo,35.679206,139.769727,35.679206,139.769727,八重洲2丁目2-7,JP,NaN,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo,"[{'fsq_id': '5c4a3ffba879210039eddadf', 'name'...",NaN,NaN,NaN,NaN,0.988267,8.6,['bath houses'],"[{'created_at': '2016-09-06T15:24:42.000Z', 't...",False,https://www.superhotel.co.jp/s_hotels/yaesu/,NaN,False,False,NaN,[],2.584970e+14,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,90,6021eac0dc86d61c512b9d92,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],31759,/v3/places/6021eac0dc86d61c512b9d92,LINK FOREST,Asia/Tokyo,35.619700,139.421640,35.619700,139.421640,鶴牧3丁目5-3,JP,NaN,"鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034",Tama,206-0034,Tokyo,"[{'fsq_id': '5df6c50db66e960008bf5b50', 'name'...",NaN,NaN,NaN,NaN,0.992253,NaN,NaN,"[{'created_at': '2021-03-25T23:26:29.000Z', 't...",False,https://link-forest.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN,NaN
91,91,513805a1e4b032c75badf416,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],34743,/v3/places/513805a1e4b032c75badf416,ホテルココアミルク,Asia/Tokyo,36.006641,139.788515,NaN,NaN,立野276-1,JP,NaN,"立野276-1, 春日部市, Saitama, 344-0134",Kasukabe,344-0134,Saitama,NaN,NaN,NaN,NaN,NaN,0.983966,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN,NaN
92,92,4dd0e28452b1f8915bd0e895,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],41385,/v3/places/4dd0e28452b1f8915bd0e895,ホテルルートイン水海道駅前,Asia/Tokyo,36.017496,139.991883,36.017496,139.991883,水海道宝町1555-2,JP,水海道宝町,"水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023",Jōsō-shi,303-0023,Ibaraki,NaN,NaN,NaN,NaN,NaN,0.991480,NaN,NaN,[],False,http://www.route-inn.co.jp/search/hotel/index....,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN,NaN
93,93,4c5d77ad94fd0f470665cb45,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],65615,/v3/places/4c5d77ad94fd0f470665cb45,ホテルシティーフィールドかごはら,Asia/Tokyo,36.173067,139.331743,36.173067,139.331743,籠原南1-123,JP,NaN,"籠原南1-123, 熊谷市, Saitama, 360-0847",Kumagaya,360-0847,Saitama,NaN,NaN,NaN,NaN,NaN,0.960615,NaN,NaN,"[{'created_at': '2019-06-01T13:30:49.000Z', 't...",False,http://www.hotel-cityfield.co.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN,NaN
94,94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,Asia/Tokyo,35.818861,140.724906,NaN,NaN,太田129-23,JP,NaN,"太田129-23, 神栖市, Ibaraki, 314-0254",NaN,314-0254,Ibaraki,NaN,NaN,NaN,NaN,NaN,0.990899,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN,NaN

In [ ]:
data.isnull().sum()

Unnamed: 0                       0
fsq_id                           0
categories                       0
chains                           0
distance                         0
link                             0
name                             0
timezone                         0
geocodes.main.latitude           0
geocodes.main.longitude          0
geocodes.roof.latitude          18
geocodes.roof.longitude         18
location.address                 1
location.country                 0
location.cross_street           87
location.formatted_address       0
location.locality                1
location.postcode                1
location.region                  0
related_places.children         29
location.address_extended       66
related_places.parent.fsq_id    85
related_places.parent.name      85
location.neighborhood           81
popularity                       0
rating                          28
tastes                          60
tips                             0
verified                         0
website                          5
hours.display                   70
hours.is_local_holiday           0
hours.open_now                   0
hours.regular                   70
hours.seasonal                   0
social_media.facebook_id        62
social_media.twitter            63
description                     89
social_media.instagram          77
price                           94
dtype: int64

### Get rid of those goddamn Dots on column name

In [ ]:
col = list(data.columns)
col

['Unnamed: 0',
 'fsq_id',
 'categories',
 'chains',
 'distance',
 'link',
 'name',
 'timezone',
 'geocodes.main.latitude',
 'geocodes.main.longitude',
 'geocodes.roof.latitude',
 'geocodes.roof.longitude',
 'location.address',
 'location.country',
 'location.cross_street',
 'location.formatted_address',
 'location.locality',
 'location.postcode',
 'location.region',
 'related_places.children',
 'location.address_extended',
 'related_places.parent.fsq_id',
 'related_places.parent.name',
 'location.neighborhood',
 'popularity',
 'rating',
 'tastes',
 'tips',
 'verified',
 'website',
 'hours.display',
 'hours.is_local_holiday',
 'hours.open_now',
 'hours.regular',
 'hours.seasonal',
 'social_media.facebook_id',
 'social_media.twitter',
 'description',
 'social_media.instagram',
 'price']

In [ ]:
column_names = {}
col_new = []

for n, x in enumerate(data.columns):
  new = x.replace('.','_')
  col_new.append(new)

  column_names[col[n]] = col_new[n]

print('大丈夫')

大丈夫

In [ ]:
column_names

{'Unnamed: 0': 'Unnamed: 0',
 'categories': 'categories',
 'chains': 'chains',
 'description': 'description',
 'distance': 'distance',
 'fsq_id': 'fsq_id',
 'geocodes.main.latitude': 'geocodes_main_latitude',
 'geocodes.main.longitude': 'geocodes_main_longitude',
 'geocodes.roof.latitude': 'geocodes_roof_latitude',
 'geocodes.roof.longitude': 'geocodes_roof_longitude',
 'hours.display': 'hours_display',
 'hours.is_local_holiday': 'hours_is_local_holiday',
 'hours.open_now': 'hours_open_now',
 'hours.regular': 'hours_regular',
 'hours.seasonal': 'hours_seasonal',
 'link': 'link',
 'location.address': 'location_address',
 'location.address_extended': 'location_address_extended',
 'location.country': 'location_country',
 'location.cross_street': 'location_cross_street',
 'location.formatted_address': 'location_formatted_address',
 'location.locality': 'location_locality',
 'location.neighborhood': 'location_neighborhood',
 'location.postcode': 'location_postcode',
 'location.region': 'location_region',
 'name': 'name',
 'popularity': 'popularity',
 'price': 'price',
 'rating': 'rating',
 'related_places.children': 'related_places_children',
 'related_places.parent.fsq_id': 'related_places_parent_fsq_id',
 'related_places.parent.name': 'related_places_parent_name',
 'social_media.facebook_id': 'social_media_facebook_id',
 'social_media.instagram': 'social_media_instagram',
 'social_media.twitter': 'social_media_twitter',
 'tastes': 'tastes',
 'timezone': 'timezone',
 'tips': 'tips',
 'verified': 'verified',
 'website': 'website'}

In [ ]:
data.rename(columns=column_names, inplace=True)

In [ ]:
data.head()

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,location_address_extended,related_places_parent_fsq_id,related_places_parent_name,location_neighborhood,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,description,social_media_instagram,price
0,0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),Asia/Tokyo,35.697955,139.770792,35.697955,139.770792,外神田1丁目2-12,JP,NaN,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,[],NaN,NaN,NaN,NaN,0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't...",False,https://www.anshin-oyado.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...","[{'closed': True, 'hours': [{'close': '+0000',...",5.511922e+14,NaN,NaN,NaN,NaN
1,1,517089e9e4b0d21e986153c3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2776,/v3/places/517089e9e4b0d21e986153c3,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,Asia/Tokyo,35.679886,139.737048,35.679886,139.737048,紀尾井町1-2,JP,NaN,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo,"[{'fsq_id': '57a6b47e498ed8c9b2ac1db1', 'name'...",ザ プリンスギャラリー東京紀尾井町 34F,552f81cc498ed8c8eab7eb25,フレッシュネスバーガー東京ガーデンテラス紀尾井町,NaN,0.997768,9.0,"['friendly staff', 'scenic views', 'hotel', 'b...","[{'created_at': '2019-03-03T02:13:09.000Z', 't...",True,https://www.princehotels.co.jp/kioicho/,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],7.888628e+14,NaN,"The Prince Gallery Tokyo Kioicho, a Luxury Col...",princegallerytokyokioicho,NaN
2,2,4f80f0bae4b0e160b9c9e122,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2480,/v3/places/4f80f0bae4b0e160b9c9e122,Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧),Asia/Tokyo,35.712912,139.777796,35.712912,139.777796,上野7丁目2-16,JP,NaN,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo,NaN,NaN,NaN,NaN,NaN,0.991224,8.7,"['saunas', 'open-air bath', 'cold-water bath']","[{'created_at': '2021-12-06T00:50:18.000Z', 't...",False,http://www.saunahokuou.com,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,hokuo8000,NaN,sauna.capsule.hokuo,NaN
3,3,598970be35f9830771f06b3f,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],3106,/v3/places/598970be35f9830771f06b3f,APA Hotel Asakusa Tawaramachi-Ekimae (アパホテル 浅草...,Asia/Tokyo,35.710112,139.790113,35.710112,139.790113,西浅草1丁目2-3,JP,NaN,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo,"[{'fsq_id': '598c3750fdb9a7339cad21c7', 'name'...",NaN,NaN,NaN,['浅草'],0.993129,8.7,NaN,"[{'created_at': '2020-02-11T07:46:18.000Z', 't...",False,https://www.apahotel.com/hotel/shutoken/asakus...,NaN,False,False,NaN,[],9.189654e+14,_apahotel,NaN,apahotel_official,NaN
4,4,5211312e11d259e1a2b3385a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],1969,/v3/places/5211312e11d259e1a2b3385a,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,Asia/Tokyo,35.679206,139.769727,35.679206,139.769727,八重洲2丁目2-7,JP,NaN,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo,"[{'fsq_id': '5c4a3ffba879210039eddadf', 'name'...",NaN,NaN,NaN,NaN,0.988267,8.6,['bath houses'],"[{'created_at': '2016-09-06T15:24:42.000Z', 't...",False,https://www.superhotel.co.jp/s_hotels/yaesu/,NaN,False,False,NaN,[],2.584970e+14,NaN,NaN,NaN,NaN

### Limpeza

In [ ]:
data.isnull().sum()

Unnamed: 0                       0
fsq_id                           0
categories                       0
chains                           0
distance                         0
link                             0
name                             0
timezone                         0
geocodes_main_latitude           0
geocodes_main_longitude          0
geocodes_roof_latitude          18
geocodes_roof_longitude         18
location_address                 1
location_country                 0
location_cross_street           87
location_formatted_address       0
location_locality                1
location_postcode                1
location_region                  0
related_places_children         29
location_address_extended       66
related_places_parent_fsq_id    85
related_places_parent_name      85
location_neighborhood           81
popularity                       0
rating                          28
tastes                          60
tips                             0
verified                         0
website                          5
hours_display                   70
hours_is_local_holiday           0
hours_open_now                   0
hours_regular                   70
hours_seasonal                   0
social_media_facebook_id        62
social_media_twitter            63
description                     89
social_media_instagram          77
price                           94
dtype: int64

In [ ]:
# Colunas com 1 valor nulo
'''
location_address : 48
location_locality : 94 = Kamisu
location_postcode : 48
'''

'\nlocation_address : 48\nlocation_locality : 94 = Kamisu\nlocation_postcode : 48\n'

In [ ]:
data[['location_locality','location_formatted_address', ]]

   location_locality                   location_formatted_address
0              Tokyo            外神田1丁目2-12, 千代田区, Tokyo, 101-0021
1            Chiyoda               紀尾井町1-2, 千代田区, Tokyo, 102-0094
2              Tokyo              上野7丁目2-16, 台東区, Tokyo, 110-0005
3              Tokyo              西浅草1丁目2-3, 台東区, Tokyo, 111-0035
4               Chuo              八重洲2丁目2-7, 中央区, Tokyo, 104-0028
..               ...                                          ...
90              Tama               鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034
91          Kasukabe             立野276-1, 春日部市, Saitama, 344-0134
92          Jōsō-shi  水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023
93          Kumagaya             籠原南1-123, 熊谷市, Saitama, 360-0847
94               NaN             太田129-23, 神栖市, Ibaraki, 314-0254

[95 rows x 2 columns]

In [ ]:
teste_pra_ver_um_negocio = pd.DataFrame(data.isnull().sum())

In [ ]:
teste_pra_ver_um_negocio.T

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,location_address_extended,related_places_parent_fsq_id,related_places_parent_name,location_neighborhood,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,description,social_media_instagram,price
0,0,0,0,0,0,0,0,0,0,0,18,18,1,0,87,0,1,1,0,29,66,85,85,81,0,28,60,0,0,5,70,0,0,70,0,62,63,89,77,94

In [ ]:
data[data['location_locality'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,location_address_extended,related_places_parent_fsq_id,related_places_parent_name,location_neighborhood,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,description,social_media_instagram,price
94,94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,Asia/Tokyo,35.818861,140.724906,NaN,NaN,太田129-23,JP,NaN,"太田129-23, 神栖市, Ibaraki, 314-0254",NaN,314-0254,Ibaraki,NaN,NaN,NaN,NaN,NaN,0.990899,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN,NaN

### Drop useless columns

In [ ]:
data.drop(columns=[ 'geocodes_roof_latitude',
                    'geocodes_roof_longitude',
                    'location_country',
                    'location_cross_street',
                    'location_address_extended',
                   	'related_places_parent_fsq_id',
                    'related_places_parent_name',
                    'location_neighborhood',
                    'description'], inplace=True)

### Limpeza

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  95 non-null     int64
 1   fsq_id                      95 non-null     object
 2   categories                  95 non-null     object
 3   chains                      95 non-null     object
 4   distance                    95 non-null     int64
 5   link                        95 non-null     object
 6   name                        95 non-null     object
 7   timezone                    95 non-null     object
 8   geocodes_main_latitude      95 non-null     float64
 9   geocodes_main_longitude     95 non-null     float64
 10  location_address            94 non-null     object
 11  location_formatted_address  95 non-null     object
 12  location_locality           94 non-null     object
 13  location_postcode           94 non-null     object
 14  location_region             95 non-null     object
 15  related_places_children     66 non-null     object
 16  popularity                  95 non-null     float64
 17  rating                      67 non-null     float64
 18  tastes                      35 non-null     object
 19  tips                        95 non-null     object
 20  verified                    95 non-null     bool
 21  website                     90 non-null     object
 22  hours_display               25 non-null     object
 23  hours_is_local_holiday      95 non-null     bool
 24  hours_open_now              95 non-null     bool
 25  hours_regular               25 non-null     object
 26  hours_seasonal              95 non-null     object
 27  social_media_facebook_id    33 non-null     float64
 28  social_media_twitter        32 non-null     object
 29  social_media_instagram      18 non-null     object
 30  price                       1 non-null      float64
dtypes: bool(3), float64(6), int64(2), object(20)
memory usage: 21.2+ KB

In [ ]:
data.isnull().sum()

Unnamed: 0                     0
fsq_id                         0
categories                     0
chains                         0
distance                       0
link                           0
name                           0
timezone                       0
geocodes_main_latitude         0
geocodes_main_longitude        0
location_address               1
location_formatted_address     0
location_locality              1
location_postcode              1
location_region                0
related_places_children       29
popularity                     0
rating                        28
tastes                        60
tips                           0
verified                       0
website                        5
hours_display                 70
hours_is_local_holiday         0
hours_open_now                 0
hours_regular                 70
hours_seasonal                 0
social_media_facebook_id      62
social_media_twitter          63
social_media_instagram        77
price                         94
dtype: int64

### 'location_locality' Nulo para 'Kamisu'

In [ ]:
data[data['location_locality'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
94,94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,Asia/Tokyo,35.818861,140.724906,太田129-23,"太田129-23, 神栖市, Ibaraki, 314-0254",NaN,314-0254,Ibaraki,NaN,0.990899,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN

In [ ]:
data[['location_address',	'location_formatted_address',	'location_locality',	'location_postcode',	'location_region']]

,location_address,location_formatted_address,location_locality,location_postcode,location_region
0,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo
1,紀尾井町1-2,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo
2,上野7丁目2-16,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo
3,西浅草1丁目2-3,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo
4,八重洲2丁目2-7,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo
...,...,...,...,...,...
90,鶴牧3丁目5-3,"鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034",Tama,206-0034,Tokyo
91,立野276-1,"立野276-1, 春日部市, Saitama, 344-0134",Kasukabe,344-0134,Saitama
92,水海道宝町1555-2,"水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023",Jōsō-shi,303-0023,Ibaraki
93,籠原南1-123,"籠原南1-123, 熊谷市, Saitama, 360-0847",Kumagaya,360-0847,Saitama
94,太田129-23,"太田129-23, 神栖市, Ibaraki, 314-0254",NaN,314-0254,Ibaraki

In [ ]:
data['location_region'].value_counts()

Tokyo       59
Kanagawa    12
Chiba        9
Saitama      8
Shizuoka     3
Ibaraki      2
Gunma        1
Tochigi      1
Name: location_region, dtype: int64

In [ ]:
data['location_locality'].sort_values().unique().tolist()

['Akiruno',
 'Atami',
 'Chiba',
 'Chichibu',
 'Chiyoda',
 'Chuo',
 'Fuchu',
 'Fussa',
 'Gotenba-shi',
 'Inagi-shi',
 'Jōsō-shi',
 'Kasukabe',
 'Katsuura',
 'Kawasaki',
 'Kumagaya',
 'Kōtō',
 'Machida',
 'Meguro',
 'Minato',
 'Mishima',
 'Musashino',
 'Narita',
 'Saitama-shi',
 'Shibayama-machi',
 'Shibuya',
 'Shiki',
 'Shinagawa',
 'Shinjuku',
 'Tachikawa-shi',
 'Tama',
 'Tokorozawa',
 'Tokyo',
 'Urayasu',
 'Utsunomiya',
 'Yokohama',
 'Ōta',
 nan]

In [ ]:
data.iloc[94]['location_locality']

nan

In [ ]:
data['location_locality'].fillna('Kamisu', inplace=True)

In [ ]:
data.isnull().sum()

Unnamed: 0                     0
fsq_id                         0
categories                     0
chains                         0
distance                       0
link                           0
name                           0
timezone                       0
geocodes_main_latitude         0
geocodes_main_longitude        0
location_address               1
location_formatted_address     0
location_locality              0
location_postcode              1
location_region                0
related_places_children       29
popularity                     0
rating                        28
tastes                        60
tips                           0
verified                       0
website                        5
hours_display                 70
hours_is_local_holiday         0
hours_open_now                 0
hours_regular                 70
hours_seasonal                 0
social_media_facebook_id      62
social_media_twitter          63
social_media_instagram        77
price                         94
dtype: int64

In [ ]:
data.iloc[94]['location_locality']

'Kamisu'

### 'location_postcode' Nulo para '197-0011' & 'location_address' para ...
Endereço: Crabb Ave, Fussa, Nishitama District, Tokyo, Tokyo 197-0011, Japan

In [ ]:
data[data['location_postcode'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
48,48,4b50466ff964a520941f27e3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],38297,/v3/places/4b50466ff964a520941f27e3,Kanto Lodge - Yokota AB,Asia/Tokyo,35.747525,139.340509,NaN,"福生市, Tokyo",Fussa,NaN,Tokyo,NaN,0.99452,7.6,NaN,"[{'created_at': '2021-06-07T21:09:59.000Z', 't...",False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN

In [ ]:
data.iloc[48]['location_postcode']

nan

In [ ]:
data['location_postcode'].fillna('197-0011', inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  95 non-null     int64
 1   fsq_id                      95 non-null     object
 2   categories                  95 non-null     object
 3   chains                      95 non-null     object
 4   distance                    95 non-null     int64
 5   link                        95 non-null     object
 6   name                        95 non-null     object
 7   timezone                    95 non-null     object
 8   geocodes_main_latitude      95 non-null     float64
 9   geocodes_main_longitude     95 non-null     float64
 10  location_address            94 non-null     object
 11  location_formatted_address  95 non-null     object
 12  location_locality           95 non-null     object
 13  location_postcode           95 non-null     object
 14  location_region             95 non-null     object
 15  related_places_children     66 non-null     object
 16  popularity                  95 non-null     float64
 17  rating                      67 non-null     float64
 18  tastes                      35 non-null     object
 19  tips                        95 non-null     object
 20  verified                    95 non-null     bool
 21  website                     90 non-null     object
 22  hours_display               25 non-null     object
 23  hours_is_local_holiday      95 non-null     bool
 24  hours_open_now              95 non-null     bool
 25  hours_regular               25 non-null     object
 26  hours_seasonal              95 non-null     object
 27  social_media_facebook_id    33 non-null     float64
 28  social_media_twitter        32 non-null     object
 29  social_media_instagram      18 non-null     object
 30  price                       1 non-null      float64
dtypes: bool(3), float64(6), int64(2), object(20)
memory usage: 21.2+ KB

In [ ]:
data.iloc[48]['location_postcode']

'197-0011'

In [ ]:
data[data['location_address'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
48,48,4b50466ff964a520941f27e3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],38297,/v3/places/4b50466ff964a520941f27e3,Kanto Lodge - Yokota AB,Asia/Tokyo,35.747525,139.340509,NaN,"福生市, Tokyo",Fussa,197-0011,Tokyo,NaN,0.99452,7.6,NaN,"[{'created_at': '2021-06-07T21:09:59.000Z', 't...",False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN

In [ ]:
data.head() 
# Crabb Ave, Fussa, Nishitama District, Tokyo, Tokyo 197-0011, Japan

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
0,0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),Asia/Tokyo,35.697955,139.770792,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,[],0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't...",False,https://www.anshin-oyado.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...","[{'closed': True, 'hours': [{'close': '+0000',...",5.511922e+14,NaN,NaN,NaN
1,1,517089e9e4b0d21e986153c3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2776,/v3/places/517089e9e4b0d21e986153c3,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,Asia/Tokyo,35.679886,139.737048,紀尾井町1-2,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo,"[{'fsq_id': '57a6b47e498ed8c9b2ac1db1', 'name'...",0.997768,9.0,"['friendly staff', 'scenic views', 'hotel', 'b...","[{'created_at': '2019-03-03T02:13:09.000Z', 't...",True,https://www.princehotels.co.jp/kioicho/,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],7.888628e+14,NaN,princegallerytokyokioicho,NaN
2,2,4f80f0bae4b0e160b9c9e122,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2480,/v3/places/4f80f0bae4b0e160b9c9e122,Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧),Asia/Tokyo,35.712912,139.777796,上野7丁目2-16,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo,NaN,0.991224,8.7,"['saunas', 'open-air bath', 'cold-water bath']","[{'created_at': '2021-12-06T00:50:18.000Z', 't...",False,http://www.saunahokuou.com,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,hokuo8000,sauna.capsule.hokuo,NaN
3,3,598970be35f9830771f06b3f,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],3106,/v3/places/598970be35f9830771f06b3f,APA Hotel Asakusa Tawaramachi-Ekimae (アパホテル 浅草...,Asia/Tokyo,35.710112,139.790113,西浅草1丁目2-3,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo,"[{'fsq_id': '598c3750fdb9a7339cad21c7', 'name'...",0.993129,8.7,NaN,"[{'created_at': '2020-02-11T07:46:18.000Z', 't...",False,https://www.apahotel.com/hotel/shutoken/asakus...,NaN,False,False,NaN,[],9.189654e+14,_apahotel,apahotel_official,NaN
4,4,5211312e11d259e1a2b3385a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],1969,/v3/places/5211312e11d259e1a2b3385a,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,Asia/Tokyo,35.679206,139.769727,八重洲2丁目2-7,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo,"[{'fsq_id': '5c4a3ffba879210039eddadf', 'name'...",0.988267,8.6,['bath houses'],"[{'created_at': '2016-09-06T15:24:42.000Z', 't...",False,https://www.superhotel.co.jp/s_hotels/yaesu/,NaN,False,False,NaN,[],2.584970e+14,NaN,NaN,NaN

In [ ]:
data['location_address'].fillna('Crabb Ave', inplace=True)

In [ ]:
data.isnull().sum()

Unnamed: 0                     0
fsq_id                         0
categories                     0
chains                         0
distance                       0
link                           0
name                           0
timezone                       0
geocodes_main_latitude         0
geocodes_main_longitude        0
location_address               0
location_formatted_address     0
location_locality              0
location_postcode              0
location_region                0
related_places_children       29
popularity                     0
rating                        28
tastes                        60
tips                           0
verified                       0
website                        5
hours_display                 70
hours_is_local_holiday         0
hours_open_now                 0
hours_regular                 70
hours_seasonal                 0
social_media_facebook_id      62
social_media_twitter          63
social_media_instagram        77
price                         94
dtype: int64

In [ ]:
data

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
0,0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),Asia/Tokyo,35.697955,139.770792,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,[],0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't...",False,https://www.anshin-oyado.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...","[{'closed': True, 'hours': [{'close': '+0000',...",5.511922e+14,NaN,NaN,NaN
1,1,517089e9e4b0d21e986153c3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2776,/v3/places/517089e9e4b0d21e986153c3,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,Asia/Tokyo,35.679886,139.737048,紀尾井町1-2,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo,"[{'fsq_id': '57a6b47e498ed8c9b2ac1db1', 'name'...",0.997768,9.0,"['friendly staff', 'scenic views', 'hotel', 'b...","[{'created_at': '2019-03-03T02:13:09.000Z', 't...",True,https://www.princehotels.co.jp/kioicho/,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],7.888628e+14,NaN,princegallerytokyokioicho,NaN
2,2,4f80f0bae4b0e160b9c9e122,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2480,/v3/places/4f80f0bae4b0e160b9c9e122,Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧),Asia/Tokyo,35.712912,139.777796,上野7丁目2-16,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo,NaN,0.991224,8.7,"['saunas', 'open-air bath', 'cold-water bath']","[{'created_at': '2021-12-06T00:50:18.000Z', 't...",False,http://www.saunahokuou.com,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,hokuo8000,sauna.capsule.hokuo,NaN
3,3,598970be35f9830771f06b3f,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],3106,/v3/places/598970be35f9830771f06b3f,APA Hotel Asakusa Tawaramachi-Ekimae (アパホテル 浅草...,Asia/Tokyo,35.710112,139.790113,西浅草1丁目2-3,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo,"[{'fsq_id': '598c3750fdb9a7339cad21c7', 'name'...",0.993129,8.7,NaN,"[{'created_at': '2020-02-11T07:46:18.000Z', 't...",False,https://www.apahotel.com/hotel/shutoken/asakus...,NaN,False,False,NaN,[],9.189654e+14,_apahotel,apahotel_official,NaN
4,4,5211312e11d259e1a2b3385a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],1969,/v3/places/5211312e11d259e1a2b3385a,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,Asia/Tokyo,35.679206,139.769727,八重洲2丁目2-7,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo,"[{'fsq_id': '5c4a3ffba879210039eddadf', 'name'...",0.988267,8.6,['bath houses'],"[{'created_at': '2016-09-06T15:24:42.000Z', 't...",False,https://www.superhotel.co.jp/s_hotels/yaesu/,NaN,False,False,NaN,[],2.584970e+14,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,90,6021eac0dc86d61c512b9d92,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],31759,/v3/places/6021eac0dc86d61c512b9d92,LINK FOREST,Asia/Tokyo,35.619700,139.421640,鶴牧3丁目5-3,"鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034",Tama,206-0034,Tokyo,"[{'fsq_id': '5df6c50db66e960008bf5b50', 'name'...",0.992253,NaN,NaN,"[{'created_at': '2021-03-25T23:26:29.000Z', 't...",False,https://link-forest.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
91,91,513805a1e4b032c75badf416,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],34743,/v3/places/513805a1e4b032c75badf416,ホテルココアミルク,Asia/Tokyo,36.006641,139.788515,立野276-1,"立野276-1, 春日部市, Saitama, 344-0134",Kasukabe,344-0134,Saitama,NaN,0.983966,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
92,92,4dd0e28452b1f8915bd0e895,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],41385,/v3/places/4dd0e28452b1f8915bd0e895,ホテルルートイン水海道駅前,Asia/Tokyo,36.017496,139.991883,水海道宝町1555-2,"水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023",Jōsō-shi,303-0023,Ibaraki,NaN,0.991480,NaN,NaN,[],False,http://www.route-inn.co.jp/search/hotel/index....,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
93,93,4c5d77ad94fd0f470665cb45,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],65615,/v3/places/4c5d77ad94fd0f470665cb45,ホテルシティーフィールドかごはら,Asia/Tokyo,36.173067,139.331743,籠原南1-123,"籠原南1-123, 熊谷市, Saitama, 360-0847",Kumagaya,360-0847,Saitama,NaN,0.960615,NaN,NaN,"[{'created_at': '2019-06-01T13:30:49.000Z', 't...",False,http://www.hotel-cityfield.co.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
94,94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,Asia/Tokyo,35.818861,140.724906,太田129-23,"太田129-23, 神栖市, Ibaraki, 314-0254",Kamisu,314-0254,Ibaraki,NaN,0.990899,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN

### Criar DataFrame com coordenadas pra acessar restaurantes brasileiros

In [ ]:
hotel_coord = data[['name', 'geocodes_main_latitude',	'geocodes_main_longitude']]

In [ ]:
# hotel_coord.to_csv('/content/drive/MyDrive/Colab/Files/PROJECT/FINALPROJECT_hotel_coordinates.csv')

## Restaurantes Brasileiros

### Limpeza

In [ ]:
brasil = pd.read_csv('/content/drive/MyDrive/Colab/Files/PROJECT/PROJETOFINAL_restaurantes.csv')
brasil

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes.main.latitude,geocodes.main.longitude,geocodes.roof.latitude,geocodes.roof.longitude,location.address,location.country,location.cross_street,location.formatted_address,location.locality,location.postcode,location.region,location.neighborhood,popularity,price,tips,verified,hours.is_local_holiday,hours.open_now,hours.seasonal,social_media.twitter,website,hours.display,hours.regular,hotel,hotel_latitude,hotel_longitude,location.address_extended,rating,related_places.parent.fsq_id,related_places.parent.name,description,tastes,social_media.facebook_id,social_media.instagram
0,0,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],734.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,b91c2784f0b44e826bdfef64,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",[],372.0,/v3/places/b91c2784f0b44e826bdfef64,TUCANO'S GRILL and BAR,NaN,35.698788,139.774789,35.698788,139.774789,神田花岡町1-1,JP,NaN,"神田花岡町1-1, 千代田区, 東京都, 101-0028",千代田区,101-0028,東京都,NaN,NaN,NaN,[],False,False,False,[],NaN,http://www.pj-partners.com/tucano/,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,40a90c773f0d4e7d9b05426c,"[{'id': 13031, 'name': 'Burger Joint', 'icon':...",[],383.0,/v3/places/40a90c773f0d4e7d9b05426c,トゥッカーノグリル&バー,NaN,35.699082,139.774807,35.699082,139.774807,神田花岡町1,JP,NaN,"神田花岡町1, 千代田区, 東京都, 101-0028",千代田区,101-0028,東京都,['Ochanomizu / Akihabara / Kanda'],NaN,NaN,[],False,False,False,[],NaN,http://www.pjgroup.jp/tucanos,Open Daily 10:30-23:00,"[{'close': '2300', 'day': 1, 'open': '1030'}, ...",Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,56738a44498e84771b21395a,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],432.0,/v3/places/56738a44498e84771b21395a,Brasilica Grill Churrascaria (ブラジリカ グリル),Asia/Tokyo,35.675996,139.736733,35.675996,139.736733,赤坂3丁目10-4,JP,風月堂ビル 5F,"赤坂3丁目10-4 (風月堂ビル 5F), 港区, Tokyo, 107-0052",Tokyo,107-0052,Tokyo,NaN,0.829911,2.0,"[{'created_at': '2016-12-19T16:23:29.000Z', 't...",False,False,False,[],NaN,http://brasilicagrill.com,"Mon-Fri 11:30-15:00, 17:00-22:30; Sat 17:00-22:30","[{'close': '1500', 'day': 1, 'open': '1130'}, ...",The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,NaN,7.6,NaN,NaN,NaN,NaN,NaN,NaN
4,4,e91ed07f7ad74c3ca56dfe6c,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",[],756.0,/v3/places/e91ed07f7ad74c3ca56dfe6c,La10Tokyo ラテントウキョウ,NaN,35.683879,139.730263,35.683879,139.730263,四谷2-2,JP,NaN,"四谷2-2, 新宿区, 東京都, 160-0004",新宿区,160-0004,東京都,NaN,NaN,NaN,[],False,False,False,[],NaN,http://www.la10.tokyo/,NaN,NaN,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,第22相信ビル 1F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,93,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],219.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,NaN,35.466538,139.626548,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",横浜市,221-0056,神奈川県,NaN,NaN,NaN,[],False,False,False,[],NaN,http://riogrande.createrestaurants.com/jp/yoko...,NaN,NaN,Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口),35.467834,139.624715,横浜ベイクォーター 3F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,94,5f0d3896938b7c3b5e5fa837,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],405.0,/v3/places/5f0d3896938b7c3b5e5fa837,Rio grande Grill,Asia/Tokyo,35.466548,139.622226,35.466548,139.622226,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",NaN,220-0005,Kanagawa,NaN,0.952048,2.0,"[{'created_at': '2021-10-02T11:09:12.000Z', 't...",False,False,True,[],NaN,https://www.cial.co.jp/yokohama/floorguide/det...,Open Daily 11:00-23:00,"[{'close': '2300', 'day': 1, 'open': '1100'}, ...",カプセルプラス横浜,35.466405,139.617794,NaN,NaN,5efff1c033887b416670de48,ハマチカ バル&キッチン,NaN,NaN,NaN,NaN
95,95,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],792.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,NaN,35.466538,139.626548,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",横浜市,221-0056,神奈川県,NaN,NaN,NaN,[],False,False,False,[],NaN,http://riogrande.createrestaurants.com/jp/yoko...,NaN,NaN,カプセルプラス横浜,35.466405,139.617794,横浜ベイクォーター 3F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,96,535a620411d212a99bebe77b,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],696.0,/v3/places/535a620411d212a99bebe77b,RIO GRANDE GRILL 横浜ベイクォーター,Asia/Tokyo,35.466282,139.626928,35.466282,139.626928,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa,NaN,0.954174,2.0,"[{'created_at': '2020-01-05T08:16:44.000Z', 't...",False,False,True,[],riograndegrill1,http://riogrande.createrestaurants.com/jp/inde...,"Mon-Fri 11:00-14:00, 17:00-22:00; Sat-Sun 11:0...","[{'close': '1400', 'day': 1, 'open': '1100'}, ...",Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター3F エリア: 横浜駅,7.5,4b1b455df964a52067fa23e3,アロハテーブル Aloha Table 横浜ベイクォーター,NaN,"['lunch', 'good for working', 'cozy', 'good fo...",2.599924e+14,riograndegrill_official
97,97,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],735.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,NaN,35.466538,139.626548,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",横浜市,221-0056,神奈川県,NaN,NaN,NaN,[],False,False,False,[],NaN,http://riogrande.createrestaurants.com/jp/yoko...,NaN,NaN,Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター 3F,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
brasil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 42 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    98 non-null     int64
 1   fsq_id                        98 non-null     object
 2   categories                    98 non-null     object
 3   chains                        98 non-null     object
 4   distance                      98 non-null     float64
 5   link                          98 non-null     object
 6   name                          98 non-null     object
 7   timezone                      58 non-null     object
 8   geocodes.main.latitude        98 non-null     float64
 9   geocodes.main.longitude       98 non-null     float64
 10  geocodes.roof.latitude        81 non-null     float64
 11  geocodes.roof.longitude       81 non-null     float64
 12  location.address              93 non-null     object
 13  location.country              98 non-null     object
 14  location.cross_street         47 non-null     object
 15  location.formatted_address    98 non-null     object
 16  location.locality             95 non-null     object
 17  location.postcode             93 non-null     object
 18  location.region               98 non-null     object
 19  location.neighborhood         15 non-null     object
 20  popularity                    58 non-null     float64
 21  price                         58 non-null     float64
 22  tips                          98 non-null     object
 23  verified                      98 non-null     bool
 24  hours.is_local_holiday        98 non-null     bool
 25  hours.open_now                98 non-null     bool
 26  hours.seasonal                98 non-null     object
 27  social_media.twitter          8 non-null      object
 28  website                       78 non-null     object
 29  hours.display                 43 non-null     object
 30  hours.regular                 46 non-null     object
 31  hotel                         98 non-null     object
 32  hotel_latitude                98 non-null     float64
 33  hotel_longitude               98 non-null     float64
 34  location.address_extended     38 non-null     object
 35  rating                        16 non-null     float64
 36  related_places.parent.fsq_id  21 non-null     object
 37  related_places.parent.name    21 non-null     object
 38  description                   4 non-null      object
 39  tastes                        13 non-null     object
 40  social_media.facebook_id      17 non-null     float64
 41  social_media.instagram        7 non-null      object
dtypes: bool(3), float64(11), int64(1), object(27)
memory usage: 30.3+ KB

In [ ]:
brasil.isnull().sum()

Unnamed: 0                       0
fsq_id                           0
categories                       0
chains                           0
distance                         0
link                             0
name                             0
timezone                        40
geocodes.main.latitude           0
geocodes.main.longitude          0
geocodes.roof.latitude          17
geocodes.roof.longitude         17
location.address                 5
location.country                 0
location.cross_street           51
location.formatted_address       0
location.locality                3
location.postcode                5
location.region                  0
location.neighborhood           83
popularity                      40
price                           40
tips                             0
verified                         0
hours.is_local_holiday           0
hours.open_now                   0
hours.seasonal                   0
social_media.twitter            90
website                         20
hours.display                   55
hours.regular                   52
hotel                            0
hotel_latitude                   0
hotel_longitude                  0
location.address_extended       60
rating                          82
related_places.parent.fsq_id    77
related_places.parent.name      77
description                     94
tastes                          85
social_media.facebook_id        81
social_media.instagram          91
dtype: int64

### Transformar ' . ' em '_' aos nomes de colunas

In [ ]:
col = list(brasil.columns)
col

['Unnamed: 0',
 'fsq_id',
 'categories',
 'chains',
 'distance',
 'link',
 'name',
 'timezone',
 'geocodes.main.latitude',
 'geocodes.main.longitude',
 'geocodes.roof.latitude',
 'geocodes.roof.longitude',
 'location.address',
 'location.country',
 'location.cross_street',
 'location.formatted_address',
 'location.locality',
 'location.postcode',
 'location.region',
 'location.neighborhood',
 'popularity',
 'price',
 'tips',
 'verified',
 'hours.is_local_holiday',
 'hours.open_now',
 'hours.seasonal',
 'social_media.twitter',
 'website',
 'hours.display',
 'hours.regular',
 'hotel',
 'hotel_latitude',
 'hotel_longitude',
 'location.address_extended',
 'rating',
 'related_places.parent.fsq_id',
 'related_places.parent.name',
 'description',
 'tastes',
 'social_media.facebook_id',
 'social_media.instagram']

In [ ]:
column_names = {}
col_new = []

for n, x in enumerate(brasil.columns):
  new = x.replace('.','_')
  col_new.append(new)

  column_names[col[n]] = col_new[n]

print('daijoubu')

daijoubu

In [ ]:
column_names

{'Unnamed: 0': 'Unnamed: 0',
 'categories': 'categories',
 'chains': 'chains',
 'description': 'description',
 'distance': 'distance',
 'fsq_id': 'fsq_id',
 'geocodes.main.latitude': 'geocodes_main_latitude',
 'geocodes.main.longitude': 'geocodes_main_longitude',
 'geocodes.roof.latitude': 'geocodes_roof_latitude',
 'geocodes.roof.longitude': 'geocodes_roof_longitude',
 'hotel': 'hotel',
 'hotel_latitude': 'hotel_latitude',
 'hotel_longitude': 'hotel_longitude',
 'hours.display': 'hours_display',
 'hours.is_local_holiday': 'hours_is_local_holiday',
 'hours.open_now': 'hours_open_now',
 'hours.regular': 'hours_regular',
 'hours.seasonal': 'hours_seasonal',
 'link': 'link',
 'location.address': 'location_address',
 'location.address_extended': 'location_address_extended',
 'location.country': 'location_country',
 'location.cross_street': 'location_cross_street',
 'location.formatted_address': 'location_formatted_address',
 'location.locality': 'location_locality',
 'location.neighborhood': 'location_neighborhood',
 'location.postcode': 'location_postcode',
 'location.region': 'location_region',
 'name': 'name',
 'popularity': 'popularity',
 'price': 'price',
 'rating': 'rating',
 'related_places.parent.fsq_id': 'related_places_parent_fsq_id',
 'related_places.parent.name': 'related_places_parent_name',
 'social_media.facebook_id': 'social_media_facebook_id',
 'social_media.instagram': 'social_media_instagram',
 'social_media.twitter': 'social_media_twitter',
 'tastes': 'tastes',
 'timezone': 'timezone',
 'tips': 'tips',
 'verified': 'verified',
 'website': 'website'}

In [ ]:
brasil.rename(columns=column_names, inplace=True)

In [ ]:
brasil.head(2)

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
0,0,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],734.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,b91c2784f0b44e826bdfef64,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",[],372.0,/v3/places/b91c2784f0b44e826bdfef64,TUCANO'S GRILL and BAR,NaN,35.698788,139.774789,35.698788,139.774789,神田花岡町1-1,JP,NaN,"神田花岡町1-1, 千代田区, 東京都, 101-0028",千代田区,101-0028,東京都,NaN,NaN,NaN,[],False,False,False,[],NaN,http://www.pj-partners.com/tucano/,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Limpeza

In [ ]:
brasil.isnull().sum()

Unnamed: 0                       0
fsq_id                           0
categories                       0
chains                           0
distance                         0
link                             0
name                             0
timezone                        40
geocodes_main_latitude           0
geocodes_main_longitude          0
geocodes_roof_latitude          17
geocodes_roof_longitude         17
location_address                 5
location_country                 0
location_cross_street           51
location_formatted_address       0
location_locality                3
location_postcode                5
location_region                  0
location_neighborhood           83
popularity                      40
price                           40
tips                             0
verified                         0
hours_is_local_holiday           0
hours_open_now                   0
hours_seasonal                   0
social_media_twitter            90
website                         20
hours_display                   55
hours_regular                   52
hotel                            0
hotel_latitude                   0
hotel_longitude                  0
location_address_extended       60
rating                          82
related_places_parent_fsq_id    77
related_places_parent_name      77
description                     94
tastes                          85
social_media_facebook_id        81
social_media_instagram          91
dtype: int64

In [ ]:
brasil[brasil['location_postcode'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
0,0,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],734.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,4e0f02e17d8bb178a8ae4e52,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],485.0,/v3/places/4e0f02e17d8bb178a8ae4e52,Copacabana 3355,Asia/Tokyo,35.446283,139.637295,35.446283,139.637295,NaN,JP,NaN,"横浜市, Kanagawa",Yokohama,NaN,Kanagawa,NaN,0.018744,2.0,"[{'created_at': '2012-05-18T14:44:04.000Z', 't...",False,False,False,[],NaN,NaN,NaN,NaN,Daiwa Roynet Hotel Yokohama-Kannai (ダイワロイネットホテ...,35.443390,139.633391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,4e0f02e17d8bb178a8ae4e52,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],733.0,/v3/places/4e0f02e17d8bb178a8ae4e52,Copacabana 3355,Asia/Tokyo,35.446283,139.637295,35.446283,139.637295,NaN,JP,NaN,"横浜市, Kanagawa",Yokohama,NaN,Kanagawa,NaN,0.018744,2.0,"[{'created_at': '2012-05-18T14:44:04.000Z', 't...",False,False,False,[],NaN,NaN,NaN,NaN,Navios Yokohama (ナビオス横浜),35.452716,139.639089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,48,8c1c030fe8db4f5b6a601481,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],208.0,/v3/places/8c1c030fe8db4f5b6a601481,ブレン・ブレン・ブレン,NaN,35.657092,139.697088,35.657092,139.697088,道玄坂1丁目17-12,JP,NaN,"道玄坂1丁目17-12, 渋谷区, 東京都",渋谷区,NaN,東京都,NaN,NaN,NaN,[],False,False,False,[],NaN,http://blenblenblen.jp/blog/,NaN,NaN,APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,野々ビル2F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,72,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],769.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Korean YMCA Asia Youth Center in Japan (YMCAアジ...,35.700045,139.758409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
brasil.columns

Index(['Unnamed: 0', 'fsq_id', 'categories', 'chains', 'distance', 'link',
       'name', 'timezone', 'geocodes_main_latitude', 'geocodes_main_longitude',
       'geocodes_roof_latitude', 'geocodes_roof_longitude', 'location_address',
       'location_country', 'location_cross_street',
       'location_formatted_address', 'location_locality', 'location_postcode',
       'location_region', 'location_neighborhood', 'popularity', 'price',
       'tips', 'verified', 'hours_is_local_holiday', 'hours_open_now',
       'hours_seasonal', 'social_media_twitter', 'website', 'hours_display',
       'hours_regular', 'hotel', 'hotel_latitude', 'hotel_longitude',
       'location_address_extended', 'rating', 'related_places_parent_fsq_id',
       'related_places_parent_name', 'description', 'tastes',
       'social_media_facebook_id', 'social_media_instagram'],
      dtype='object')

In [ ]:
brasil[['location_address', 'location_country', 'location_cross_street', 'location_formatted_address', 'location_locality', 'location_postcode', 'location_region']]

,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region
0,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo
1,神田花岡町1-1,JP,NaN,"神田花岡町1-1, 千代田区, 東京都, 101-0028",千代田区,101-0028,東京都
2,神田花岡町1,JP,NaN,"神田花岡町1, 千代田区, 東京都, 101-0028",千代田区,101-0028,東京都
3,赤坂3丁目10-4,JP,風月堂ビル 5F,"赤坂3丁目10-4 (風月堂ビル 5F), 港区, Tokyo, 107-0052",Tokyo,107-0052,Tokyo
4,四谷2-2,JP,NaN,"四谷2-2, 新宿区, 東京都, 160-0004",新宿区,160-0004,東京都
...,...,...,...,...,...,...,...
93,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",横浜市,221-0056,神奈川県
94,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",NaN,220-0005,Kanagawa
95,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",横浜市,221-0056,神奈川県
96,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa
97,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",横浜市,221-0056,神奈川県

### 'location_region' into romaji

In [ ]:
brasil['location_region'].unique()

array(['Tokyo', '東京都', 'Chiba', 'Kanagawa', '神奈川県', '千葉県'], dtype=object)

In [ ]:
data['location_region'].unique()

array(['Tokyo', 'Chiba', 'Kanagawa', 'Saitama', 'Gunma', 'Shizuoka',
       'Tochigi', 'Ibaraki'], dtype=object)

In [ ]:
ken = { '千葉県':'Chiba',
        '群馬県':'Gunma',
        '東京都':'Tokyo',
        '神奈川県':'Kanagawa',
        '埼玉県':'Saitama',
        '栃木県':'Tochigi'}

In [ ]:
brasil['location_region'].replace(ken, inplace=True)

In [ ]:
brasil['location_region'].unique()

array(['Tokyo', 'Chiba', 'Kanagawa'], dtype=object)

### 'location_locality' into romaji

In [ ]:
brasil['location_locality'].unique()

array(['Tokyo', '千代田区', '新宿区', 'Taitō', 'Chiyoda', 'Chuo', 'Urayasu',
       'Yokohama', nan, '横浜市', 'Roppongi', 'Tachikawa-shi', "Jin'nan",
       '渋谷区', '港区', 'Kawasaki', 'Narita-shi', '成田市', '豊島区', 'Ōta', '大田区'],
      dtype=object)

In [ ]:
data['location_locality'].unique()

array(['Tokyo', 'Chiyoda', 'Chuo', 'Urayasu', 'Kawasaki', 'Minato',
       'Shinagawa', 'Machida', 'Meguro', 'Yokohama', 'Kōtō',
       'Saitama-shi', 'Tachikawa-shi', 'Shibayama-machi', 'Narita', 'Ōta',
       'Katsuura', 'Shibuya', 'Chichibu', 'Fussa', 'Gotenba-shi',
       'Utsunomiya', 'Akiruno', 'Shiki', 'Atami', 'Chiba', 'Mishima',
       'Shinjuku', 'Musashino', 'Inagi-shi', 'Fuchu', 'Tokorozawa',
       'Tama', 'Kasukabe', 'Jōsō-shi', 'Kumagaya', 'Kamisu'], dtype=object)

In [ ]:
shi = { '成田市':'Narita',
        '邑楽郡':'Ōra-gun',
        '千代田区':'Chiyoda',
        '新宿区':'Shinjuku',
        '港区':'Minato',
        '豊島区':'Toshima',
        '渋谷区':'Shibuya',
        '葛飾区':'Katsushika',
        '世田谷区':'Setagaya',
        '横浜市':'Yokohama',
        'さいたま市':'Saitama',
        '八千代市':'Yachio',
        '千葉市':'Chiba',
        '川越市':'Arihara',
        '我孫子市':'Abiko',
        '市原市':'Ichihara',
        '久喜市':'Kuki',
        '平塚市':'Hiratsuka',
        '館林市':'Tatebayashi-shi',
        '太田市':'Oota',
        '大田区':'Oota-ku',
        '真岡市':'Mooka',
        '伊勢崎市':'Isesaki'}

In [ ]:
brasil['location_locality'].replace(shi, inplace=True)

In [ ]:
brasil['location_locality'].unique()

array(['Tokyo', 'Chiyoda', 'Shinjuku', 'Taitō', 'Chuo', 'Urayasu',
       'Yokohama', nan, 'Roppongi', 'Tachikawa-shi', "Jin'nan", 'Shibuya',
       'Minato', 'Kawasaki', 'Narita-shi', 'Narita', 'Toshima', 'Ōta',
       'Oota-ku'], dtype=object)

### 'location_postcode' Nulo

In [ ]:
brasil[brasil['location_postcode'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
0,0,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],734.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,4e0f02e17d8bb178a8ae4e52,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],485.0,/v3/places/4e0f02e17d8bb178a8ae4e52,Copacabana 3355,Asia/Tokyo,35.446283,139.637295,35.446283,139.637295,NaN,JP,NaN,"横浜市, Kanagawa",Yokohama,NaN,Kanagawa,NaN,0.018744,2.0,"[{'created_at': '2012-05-18T14:44:04.000Z', 't...",False,False,False,[],NaN,NaN,NaN,NaN,Daiwa Roynet Hotel Yokohama-Kannai (ダイワロイネットホテ...,35.443390,139.633391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,4e0f02e17d8bb178a8ae4e52,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],733.0,/v3/places/4e0f02e17d8bb178a8ae4e52,Copacabana 3355,Asia/Tokyo,35.446283,139.637295,35.446283,139.637295,NaN,JP,NaN,"横浜市, Kanagawa",Yokohama,NaN,Kanagawa,NaN,0.018744,2.0,"[{'created_at': '2012-05-18T14:44:04.000Z', 't...",False,False,False,[],NaN,NaN,NaN,NaN,Navios Yokohama (ナビオス横浜),35.452716,139.639089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,48,8c1c030fe8db4f5b6a601481,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],208.0,/v3/places/8c1c030fe8db4f5b6a601481,ブレン・ブレン・ブレン,NaN,35.657092,139.697088,35.657092,139.697088,道玄坂1丁目17-12,JP,NaN,"道玄坂1丁目17-12, 渋谷区, 東京都",Shibuya,NaN,Tokyo,NaN,NaN,NaN,[],False,False,False,[],NaN,http://blenblenblen.jp/blog/,NaN,NaN,APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,野々ビル2F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,72,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],769.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,NaN,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Korean YMCA Asia Youth Center in Japan (YMCAアジ...,35.700045,139.758409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
brasil.iloc[0]

Unnamed: 0                                                                      0
fsq_id                                                   505fce2be4b0a054473fa2eb
categories                      [{'id': 13079, 'name': 'Brazilian Restaurant',...
chains                                                                         []
distance                                                                    734.0
link                                          /v3/places/505fce2be4b0a054473fa2eb
name                                                                      SAUDADE
timezone                                                               Asia/Tokyo
geocodes_main_latitude                                                  35.703322
geocodes_main_longitude                                                139.765882
geocodes_roof_latitude                                                  35.703322
geocodes_roof_longitude                                                139.765882
location_address                                                        湯島2丁目3-14
location_country                                                               JP
location_cross_street                                                    エムサ湯島 1F
location_formatted_address                       湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo
location_locality                                                           Tokyo
location_postcode                                                             NaN
location_region                                                             Tokyo
location_neighborhood                                                         NaN
popularity                                                               0.672851
price                                                                         2.0
tips                                                                           []
verified                                                                    False
hours_is_local_holiday                                                      False
hours_open_now                                                              False
hours_seasonal                                                                 []
social_media_twitter                                                          NaN
website                                                                       NaN
hours_display                                                                 NaN
hours_regular                                                                 NaN
hotel                                                 Anshin Oyado (安心お宿 秋葉原電気街店)
hotel_latitude                                                          35.697955
hotel_longitude                                                        139.770792
location_address_extended                                                     NaN
rating                                                                        NaN
related_places_parent_fsq_id                                                  NaN
related_places_parent_name                                                    NaN
description                                                                   NaN
tastes                                                                        NaN
social_media_facebook_id                                                      NaN
social_media_instagram                                                        NaN
Name: 0, dtype: object

In [ ]:
brasil['location_postcode'][0] = '113-0034'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
brasil['location_postcode'][0]

'113-0034'

### Other Nulos

In [ ]:
brasil.iloc[27]
# 27 : 3 Chome Sumiyoshicho, Naka Ward, Yokohama, Kanagawa 231-0013, Japan

Unnamed: 0                                                                     27
fsq_id                                                   4e0f02e17d8bb178a8ae4e52
categories                      [{'id': 13079, 'name': 'Brazilian Restaurant',...
chains                                                                         []
distance                                                                    485.0
link                                          /v3/places/4e0f02e17d8bb178a8ae4e52
name                                                              Copacabana 3355
timezone                                                               Asia/Tokyo
geocodes_main_latitude                                                  35.446283
geocodes_main_longitude                                                139.637295
geocodes_roof_latitude                                                  35.446283
geocodes_roof_longitude                                                139.637295
location_address                                                              NaN
location_country                                                               JP
location_cross_street                                                         NaN
location_formatted_address                                          横浜市, Kanagawa
location_locality                                                        Yokohama
location_postcode                                                             NaN
location_region                                                          Kanagawa
location_neighborhood                                                         NaN
popularity                                                               0.018744
price                                                                         2.0
tips                            [{'created_at': '2012-05-18T14:44:04.000Z', 't...
verified                                                                    False
hours_is_local_holiday                                                      False
hours_open_now                                                              False
hours_seasonal                                                                 []
social_media_twitter                                                          NaN
website                                                                       NaN
hours_display                                                                 NaN
hours_regular                                                                 NaN
hotel                           Daiwa Roynet Hotel Yokohama-Kannai (ダイワロイネットホテ...
hotel_latitude                                                           35.44339
hotel_longitude                                                        139.633391
location_address_extended                                                     NaN
rating                                                                        NaN
related_places_parent_fsq_id                                                  NaN
related_places_parent_name                                                    NaN
description                                                                   NaN
tastes                                                                        NaN
social_media_facebook_id                                                      NaN
social_media_instagram                                                        NaN
Name: 27, dtype: object

In [ ]:
brasil['location_address'][27] = '3 Chome Sumiyoshicho'
brasil['location_postcode'][27] = '231-0013'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
brasil.iloc[29]
# 29 : 3 Chome Sumiyoshicho, Naka Ward, Yokohama, Kanagawa 231-0013, Japan

Unnamed: 0                                                                     29
fsq_id                                                   4e0f02e17d8bb178a8ae4e52
categories                      [{'id': 13079, 'name': 'Brazilian Restaurant',...
chains                                                                         []
distance                                                                    733.0
link                                          /v3/places/4e0f02e17d8bb178a8ae4e52
name                                                              Copacabana 3355
timezone                                                               Asia/Tokyo
geocodes_main_latitude                                                  35.446283
geocodes_main_longitude                                                139.637295
geocodes_roof_latitude                                                  35.446283
geocodes_roof_longitude                                                139.637295
location_address                                                              NaN
location_country                                                               JP
location_cross_street                                                         NaN
location_formatted_address                                          横浜市, Kanagawa
location_locality                                                        Yokohama
location_postcode                                                             NaN
location_region                                                          Kanagawa
location_neighborhood                                                         NaN
popularity                                                               0.018744
price                                                                         2.0
tips                            [{'created_at': '2012-05-18T14:44:04.000Z', 't...
verified                                                                    False
hours_is_local_holiday                                                      False
hours_open_now                                                              False
hours_seasonal                                                                 []
social_media_twitter                                                          NaN
website                                                                       NaN
hours_display                                                                 NaN
hours_regular                                                                 NaN
hotel                                                    Navios Yokohama (ナビオス横浜)
hotel_latitude                                                          35.452716
hotel_longitude                                                        139.639089
location_address_extended                                                     NaN
rating                                                                        NaN
related_places_parent_fsq_id                                                  NaN
related_places_parent_name                                                    NaN
description                                                                   NaN
tastes                                                                        NaN
social_media_facebook_id                                                      NaN
social_media_instagram                                                        NaN
Name: 29, dtype: object

In [ ]:
brasil['location_address'][29] = '3 Chome Sumiyoshicho'
brasil['location_postcode'][29] = '231-0013'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
brasil.iloc[48]
# 48 : 1-chōme-17 Dōgenzaka, Shibuya City, Tokyo 150-0043, Japan

Unnamed: 0                                                                     48
fsq_id                                                   8c1c030fe8db4f5b6a601481
categories                      [{'id': 13079, 'name': 'Brazilian Restaurant',...
chains                                                                         []
distance                                                                    208.0
link                                          /v3/places/8c1c030fe8db4f5b6a601481
name                                                                  ブレン・ブレン・ブレン
timezone                                                                      NaN
geocodes_main_latitude                                                  35.657092
geocodes_main_longitude                                                139.697088
geocodes_roof_latitude                                                  35.657092
geocodes_roof_longitude                                                139.697088
location_address                                                      道玄坂1丁目17-12
location_country                                                               JP
location_cross_street                                                         NaN
location_formatted_address                                  道玄坂1丁目17-12, 渋谷区, 東京都
location_locality                                                         Shibuya
location_postcode                                                             NaN
location_region                                                             Tokyo
location_neighborhood                                                         NaN
popularity                                                                    NaN
price                                                                         NaN
tips                                                                           []
verified                                                                    False
hours_is_local_holiday                                                      False
hours_open_now                                                              False
hours_seasonal                                                                 []
social_media_twitter                                                          NaN
website                                              http://blenblenblen.jp/blog/
hours_display                                                                 NaN
hours_regular                                                                 NaN
hotel                                APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上)
hotel_latitude                                                          35.656304
hotel_longitude                                                        139.694989
location_address_extended                                                  野々ビル2F
rating                                                                        NaN
related_places_parent_fsq_id                                                  NaN
related_places_parent_name                                                    NaN
description                                                                   NaN
tastes                                                                        NaN
social_media_facebook_id                                                      NaN
social_media_instagram                                                        NaN
Name: 48, dtype: object

In [ ]:
brasil['location_postcode'][48] = '150-0043'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
brasil.iloc[72]
# 72 : 2-chōme-3 Yushima, Bunkyo City, Tokyo 113-0034, Japan

Unnamed: 0                                                                     72
fsq_id                                                   505fce2be4b0a054473fa2eb
categories                      [{'id': 13079, 'name': 'Brazilian Restaurant',...
chains                                                                         []
distance                                                                    769.0
link                                          /v3/places/505fce2be4b0a054473fa2eb
name                                                                      SAUDADE
timezone                                                               Asia/Tokyo
geocodes_main_latitude                                                  35.703322
geocodes_main_longitude                                                139.765882
geocodes_roof_latitude                                                  35.703322
geocodes_roof_longitude                                                139.765882
location_address                                                        湯島2丁目3-14
location_country                                                               JP
location_cross_street                                                    エムサ湯島 1F
location_formatted_address                       湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo
location_locality                                                           Tokyo
location_postcode                                                             NaN
location_region                                                             Tokyo
location_neighborhood                                                         NaN
popularity                                                               0.672851
price                                                                         2.0
tips                                                                           []
verified                                                                    False
hours_is_local_holiday                                                      False
hours_open_now                                                              False
hours_seasonal                                                                 []
social_media_twitter                                                          NaN
website                                                                       NaN
hours_display                                                                 NaN
hours_regular                                                                 NaN
hotel                           Korean YMCA Asia Youth Center in Japan (YMCAアジ...
hotel_latitude                                                          35.700045
hotel_longitude                                                        139.758409
location_address_extended                                                     NaN
rating                                                                        NaN
related_places_parent_fsq_id                                                  NaN
related_places_parent_name                                                    NaN
description                                                                   NaN
tastes                                                                        NaN
social_media_facebook_id                                                      NaN
social_media_instagram                                                        NaN
Name: 72, dtype: object

In [ ]:
brasil['location_postcode'][72] = '113-0034'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

### Limpeza

In [ ]:
brasil.isnull().sum()

Unnamed: 0                       0
fsq_id                           0
categories                       0
chains                           0
distance                         0
link                             0
name                             0
timezone                        40
geocodes_main_latitude           0
geocodes_main_longitude          0
geocodes_roof_latitude          17
geocodes_roof_longitude         17
location_address                 3
location_country                 0
location_cross_street           51
location_formatted_address       0
location_locality                3
location_postcode                0
location_region                  0
location_neighborhood           83
popularity                      40
price                           40
tips                             0
verified                         0
hours_is_local_holiday           0
hours_open_now                   0
hours_seasonal                   0
social_media_twitter            90
website                         20
hours_display                   55
hours_regular                   52
hotel                            0
hotel_latitude                   0
hotel_longitude                  0
location_address_extended       60
rating                          82
related_places_parent_fsq_id    77
related_places_parent_name      77
description                     94
tastes                          85
social_media_facebook_id        81
social_media_instagram          91
dtype: int64

### 'location_address' Nulo

In [ ]:
brasil[brasil['location_address'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
8,8,5c3dcf2c4c954c002c09b806,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],280.0,/v3/places/5c3dcf2c4c954c002c09b806,Cantinho,Asia/Tokyo,35.679147,139.772888,35.679147,139.772888,NaN,JP,NaN,"中央区, Tokyo, 103-0027",Chuo,103-0027,Tokyo,NaN,0.799686,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,35.679206,139.769727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,38,6039c959ab44fd74e65bfc17,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],305.0,/v3/places/6039c959ab44fd74e65bfc17,Alegria,Asia/Tokyo,35.697260,139.412280,NaN,NaN,NaN,JP,NaN,"立川市, Tokyo, 190-0023",Tachikawa-shi,190-0023,Tokyo,NaN,0.451123,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Toyoko Inn (東横イン 立川駅北口),35.698812,139.409486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,56,5c3dcf2c4c954c002c09b806,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],632.0,/v3/places/5c3dcf2c4c954c002c09b806,Cantinho,Asia/Tokyo,35.679147,139.772888,35.679147,139.772888,NaN,JP,NaN,"中央区, Tokyo, 103-0027",Chuo,103-0027,Tokyo,NaN,0.799686,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Smile Hotel Tokyo Nihonbashi (スマイルホテル 東京日本橋),35.678945,139.779835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 8 : 3-chōme-5 Nihonbashi, Chuo City, Tokyo 103-0027, Japan
# 38 : 3-chōme-1 Shibasakichō, Tachikawa, Tokyo 190-0023, Japan
# 56 : 3-chōme-5 Nihonbashi, Chuo City, Tokyo 103-0027, Japan

In [ ]:
brasil['location_address'][8] = '3-chōme-5 Nihonbashi'
brasil['location_address'][38] = '3-chōme-1 Shibasakichō'
brasil['location_address'][56] = '3-chōme-5 Nihonbashi'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

### 'location_locality' Nulo

In [ ]:
brasil[brasil['location_locality'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
22,22,5f0d3896938b7c3b5e5fa837,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],314.0,/v3/places/5f0d3896938b7c3b5e5fa837,Rio grande Grill,Asia/Tokyo,35.466548,139.622226,35.466548,139.622226,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",NaN,220-0005,Kanagawa,NaN,0.952048,2.0,"[{'created_at': '2021-10-02T11:09:12.000Z', 't...",False,False,True,[],NaN,https://www.cial.co.jp/yokohama/floorguide/det...,Open Daily 11:00-23:00,"[{'close': '2300', 'day': 1, 'open': '1100'}, ...",スカイスパYOKOHAMA,35.464584,139.624648,NaN,NaN,5efff1c033887b416670de48,ハマチカ バル&キッチン,NaN,NaN,NaN,NaN
92,92,5f0d3896938b7c3b5e5fa837,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],258.0,/v3/places/5f0d3896938b7c3b5e5fa837,Rio grande Grill,Asia/Tokyo,35.466548,139.622226,35.466548,139.622226,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",NaN,220-0005,Kanagawa,NaN,0.952048,2.0,"[{'created_at': '2021-10-02T11:09:12.000Z', 't...",False,False,True,[],NaN,https://www.cial.co.jp/yokohama/floorguide/det...,Open Daily 11:00-23:00,"[{'close': '2300', 'day': 1, 'open': '1100'}, ...",Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口),35.467834,139.624715,NaN,NaN,5efff1c033887b416670de48,ハマチカ バル&キッチン,NaN,NaN,NaN,NaN
94,94,5f0d3896938b7c3b5e5fa837,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],405.0,/v3/places/5f0d3896938b7c3b5e5fa837,Rio grande Grill,Asia/Tokyo,35.466548,139.622226,35.466548,139.622226,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",NaN,220-0005,Kanagawa,NaN,0.952048,2.0,"[{'created_at': '2021-10-02T11:09:12.000Z', 't...",False,False,True,[],NaN,https://www.cial.co.jp/yokohama/floorguide/det...,Open Daily 11:00-23:00,"[{'close': '2300', 'day': 1, 'open': '1100'}, ...",カプセルプラス横浜,35.466405,139.617794,NaN,NaN,5efff1c033887b416670de48,ハマチカ バル&キッチン,NaN,NaN,NaN,NaN

In [ ]:
brasil['location_locality'].unique()

array(['Tokyo', 'Chiyoda', 'Shinjuku', 'Taitō', 'Chuo', 'Urayasu',
       'Yokohama', nan, 'Roppongi', 'Tachikawa-shi', "Jin'nan", 'Shibuya',
       'Minato', 'Kawasaki', 'Narita-shi', 'Narita', 'Toshima', 'Ōta',
       'Oota-ku'], dtype=object)

In [ ]:
brasil['location_locality'][22] = 'Yokohama'
brasil['location_locality'][92] = 'Yokohama'
brasil['location_locality'][94] = 'Yokohama'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
brasil.isnull().sum()

Unnamed: 0                       0
fsq_id                           0
categories                       0
chains                           0
distance                         0
link                             0
name                             0
timezone                        40
geocodes_main_latitude           0
geocodes_main_longitude          0
geocodes_roof_latitude          17
geocodes_roof_longitude         17
location_address                 0
location_country                 0
location_cross_street           51
location_formatted_address       0
location_locality                0
location_postcode                0
location_region                  0
location_neighborhood           83
popularity                      40
price                           40
tips                             0
verified                         0
hours_is_local_holiday           0
hours_open_now                   0
hours_seasonal                   0
social_media_twitter            90
website                         20
hours_display                   55
hours_regular                   52
hotel                            0
hotel_latitude                   0
hotel_longitude                  0
location_address_extended       60
rating                          82
related_places_parent_fsq_id    77
related_places_parent_name      77
description                     94
tastes                          85
social_media_facebook_id        81
social_media_instagram          91
dtype: int64

### Timezone é igual no japao

In [ ]:
brasil['timezone'].fillna(brasil['timezone'].mode()[0], inplace=True)

In [ ]:
brasil['timezone'].value_counts()

Asia/Tokyo    98
Name: timezone, dtype: int64

### Resultado dos DataFrames

In [ ]:
data

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
0,0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),Asia/Tokyo,35.697955,139.770792,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,[],0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't...",False,https://www.anshin-oyado.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...","[{'closed': True, 'hours': [{'close': '+0000',...",5.511922e+14,NaN,NaN,NaN
1,1,517089e9e4b0d21e986153c3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2776,/v3/places/517089e9e4b0d21e986153c3,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,Asia/Tokyo,35.679886,139.737048,紀尾井町1-2,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo,"[{'fsq_id': '57a6b47e498ed8c9b2ac1db1', 'name'...",0.997768,9.0,"['friendly staff', 'scenic views', 'hotel', 'b...","[{'created_at': '2019-03-03T02:13:09.000Z', 't...",True,https://www.princehotels.co.jp/kioicho/,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],7.888628e+14,NaN,princegallerytokyokioicho,NaN
2,2,4f80f0bae4b0e160b9c9e122,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2480,/v3/places/4f80f0bae4b0e160b9c9e122,Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧),Asia/Tokyo,35.712912,139.777796,上野7丁目2-16,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo,NaN,0.991224,8.7,"['saunas', 'open-air bath', 'cold-water bath']","[{'created_at': '2021-12-06T00:50:18.000Z', 't...",False,http://www.saunahokuou.com,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,hokuo8000,sauna.capsule.hokuo,NaN
3,3,598970be35f9830771f06b3f,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],3106,/v3/places/598970be35f9830771f06b3f,APA Hotel Asakusa Tawaramachi-Ekimae (アパホテル 浅草...,Asia/Tokyo,35.710112,139.790113,西浅草1丁目2-3,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo,"[{'fsq_id': '598c3750fdb9a7339cad21c7', 'name'...",0.993129,8.7,NaN,"[{'created_at': '2020-02-11T07:46:18.000Z', 't...",False,https://www.apahotel.com/hotel/shutoken/asakus...,NaN,False,False,NaN,[],9.189654e+14,_apahotel,apahotel_official,NaN
4,4,5211312e11d259e1a2b3385a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],1969,/v3/places/5211312e11d259e1a2b3385a,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,Asia/Tokyo,35.679206,139.769727,八重洲2丁目2-7,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo,"[{'fsq_id': '5c4a3ffba879210039eddadf', 'name'...",0.988267,8.6,['bath houses'],"[{'created_at': '2016-09-06T15:24:42.000Z', 't...",False,https://www.superhotel.co.jp/s_hotels/yaesu/,NaN,False,False,NaN,[],2.584970e+14,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,90,6021eac0dc86d61c512b9d92,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],31759,/v3/places/6021eac0dc86d61c512b9d92,LINK FOREST,Asia/Tokyo,35.619700,139.421640,鶴牧3丁目5-3,"鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034",Tama,206-0034,Tokyo,"[{'fsq_id': '5df6c50db66e960008bf5b50', 'name'...",0.992253,NaN,NaN,"[{'created_at': '2021-03-25T23:26:29.000Z', 't...",False,https://link-forest.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
91,91,513805a1e4b032c75badf416,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],34743,/v3/places/513805a1e4b032c75badf416,ホテルココアミルク,Asia/Tokyo,36.006641,139.788515,立野276-1,"立野276-1, 春日部市, Saitama, 344-0134",Kasukabe,344-0134,Saitama,NaN,0.983966,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
92,92,4dd0e28452b1f8915bd0e895,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],41385,/v3/places/4dd0e28452b1f8915bd0e895,ホテルルートイン水海道駅前,Asia/Tokyo,36.017496,139.991883,水海道宝町1555-2,"水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023",Jōsō-shi,303-0023,Ibaraki,NaN,0.991480,NaN,NaN,[],False,http://www.route-inn.co.jp/search/hotel/index....,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
93,93,4c5d77ad94fd0f470665cb45,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],65615,/v3/places/4c5d77ad94fd0f470665cb45,ホテルシティーフィールドかごはら,Asia/Tokyo,36.173067,139.331743,籠原南1-123,"籠原南1-123, 熊谷市, Saitama, 360-0847",Kumagaya,360-0847,Saitama,NaN,0.960615,NaN,NaN,"[{'created_at': '2019-06-01T13:30:49.000Z', 't...",False,http://www.hotel-cityfield.co.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
94,94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,Asia/Tokyo,35.818861,140.724906,太田129-23,"太田129-23, 神栖市, Ibaraki, 314-0254",Kamisu,314-0254,Ibaraki,NaN,0.990899,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN

In [ ]:
brasil

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
0,0,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],734.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,Asia/Tokyo,35.703322,139.765882,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,113-0034,Tokyo,NaN,0.672851,2.0,[],False,False,False,[],NaN,NaN,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,b91c2784f0b44e826bdfef64,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",[],372.0,/v3/places/b91c2784f0b44e826bdfef64,TUCANO'S GRILL and BAR,Asia/Tokyo,35.698788,139.774789,35.698788,139.774789,神田花岡町1-1,JP,NaN,"神田花岡町1-1, 千代田区, 東京都, 101-0028",Chiyoda,101-0028,Tokyo,NaN,NaN,NaN,[],False,False,False,[],NaN,http://www.pj-partners.com/tucano/,NaN,NaN,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,40a90c773f0d4e7d9b05426c,"[{'id': 13031, 'name': 'Burger Joint', 'icon':...",[],383.0,/v3/places/40a90c773f0d4e7d9b05426c,トゥッカーノグリル&バー,Asia/Tokyo,35.699082,139.774807,35.699082,139.774807,神田花岡町1,JP,NaN,"神田花岡町1, 千代田区, 東京都, 101-0028",Chiyoda,101-0028,Tokyo,['Ochanomizu / Akihabara / Kanda'],NaN,NaN,[],False,False,False,[],NaN,http://www.pjgroup.jp/tucanos,Open Daily 10:30-23:00,"[{'close': '2300', 'day': 1, 'open': '1030'}, ...",Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,56738a44498e84771b21395a,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],432.0,/v3/places/56738a44498e84771b21395a,Brasilica Grill Churrascaria (ブラジリカ グリル),Asia/Tokyo,35.675996,139.736733,35.675996,139.736733,赤坂3丁目10-4,JP,風月堂ビル 5F,"赤坂3丁目10-4 (風月堂ビル 5F), 港区, Tokyo, 107-0052",Tokyo,107-0052,Tokyo,NaN,0.829911,2.0,"[{'created_at': '2016-12-19T16:23:29.000Z', 't...",False,False,False,[],NaN,http://brasilicagrill.com,"Mon-Fri 11:30-15:00, 17:00-22:30; Sat 17:00-22:30","[{'close': '1500', 'day': 1, 'open': '1130'}, ...",The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,NaN,7.6,NaN,NaN,NaN,NaN,NaN,NaN
4,4,e91ed07f7ad74c3ca56dfe6c,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",[],756.0,/v3/places/e91ed07f7ad74c3ca56dfe6c,La10Tokyo ラテントウキョウ,Asia/Tokyo,35.683879,139.730263,35.683879,139.730263,四谷2-2,JP,NaN,"四谷2-2, 新宿区, 東京都, 160-0004",Shinjuku,160-0004,Tokyo,NaN,NaN,NaN,[],False,False,False,[],NaN,http://www.la10.tokyo/,NaN,NaN,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,第22相信ビル 1F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,93,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],219.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,Asia/Tokyo,35.466538,139.626548,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",Yokohama,221-0056,Kanagawa,NaN,NaN,NaN,[],False,False,False,[],NaN,http://riogrande.createrestaurants.com/jp/yoko...,NaN,NaN,Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口),35.467834,139.624715,横浜ベイクォーター 3F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,94,5f0d3896938b7c3b5e5fa837,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],405.0,/v3/places/5f0d3896938b7c3b5e5fa837,Rio grande Grill,Asia/Tokyo,35.466548,139.622226,35.466548,139.622226,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",Yokohama,220-0005,Kanagawa,NaN,0.952048,2.0,"[{'created_at': '2021-10-02T11:09:12.000Z', 't...",False,False,True,[],NaN,https://www.cial.co.jp/yokohama/floorguide/det...,Open Daily 11:00-23:00,"[{'close': '2300', 'day': 1, 'open': '1100'}, ...",カプセルプラス横浜,35.466405,139.617794,NaN,NaN,5efff1c033887b416670de48,ハマチカ バル&キッチン,NaN,NaN,NaN,NaN
95,95,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],792.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,Asia/Tokyo,35.466538,139.626548,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",Yokohama,221-0056,Kanagawa,NaN,NaN,NaN,[],False,False,False,[],NaN,http://riogrande.createrestaurants.com/jp/yoko...,NaN,NaN,カプセルプラス横浜,35.466405,139.617794,横浜ベイクォーター 3F,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,96,535a620411d212a99bebe77b,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],696.0,/v3/places/535a620411d212a99bebe77b,RIO GRANDE GRILL 横浜ベイクォーター,Asia/Tokyo,35.466282,139.626928,35.466282,139.626928,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa,NaN,0.954174,2.0,"[{'created_at': '2020-01-05T08:16:44.000Z', 't...",False,False,True,[],riograndegrill1,http://riogrande.createrestaurants.com/jp/inde...,"Mon-Fri 11:00-14:00, 17:00-22:00; Sat-Sun 11:0...","[{'close': '1400', 'day': 1, 'open': '1100'}, ...",Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター3F エリア: 横浜駅,7.5,4b1b455df964a52067fa23e3,アロハテーブル Aloha Table 横浜ベイクォーター,NaN,"['lunch', 'good for working', 'cozy', 'good fo...",2.599924e+14,riograndegrill_official
97,97,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],735.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,Asia/Tokyo,35.466538,139.626548,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",Yokohama,221-0056,Kanagawa,NaN,NaN,NaN,[],False,False,False,[],NaN,http://riogrande.createrestaurants.com/jp/yoko...,NaN,NaN,Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター 3F,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# ToDo s

* drop useless columns;
* locality duplicada;
* folium
*

In [ ]:
data.head(1)

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
0,0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),Asia/Tokyo,35.697955,139.770792,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,[],0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't...",False,https://www.anshin-oyado.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...","[{'closed': True, 'hours': [{'close': '+0000',...",5.511922e+14,NaN,NaN,NaN

In [ ]:
data.columns

Index(['Unnamed: 0', 'fsq_id', 'categories', 'chains', 'distance', 'link',
       'name', 'timezone', 'geocodes_main_latitude', 'geocodes_main_longitude',
       'location_address', 'location_formatted_address', 'location_locality',
       'location_postcode', 'location_region', 'related_places_children',
       'popularity', 'rating', 'tastes', 'tips', 'verified', 'website',
       'hours_display', 'hours_is_local_holiday', 'hours_open_now',
       'hours_regular', 'hours_seasonal', 'social_media_facebook_id',
       'social_media_twitter', 'social_media_instagram', 'price'],
      dtype='object')

In [ ]:
data.shape

(95, 31)

### 'related_places_children' de valor '[]' para NaN

In [ ]:
data['related_places_children'][data['related_places_children']=='[]'] = np.NaN

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

### Drop Useless columns

In [ ]:
data['price'].isnull().sum()

In [ ]:
data['tips'].isnull().sum()

0

In [ ]:
data['tips'][0]

"[{'created_at': '2019-04-24T07:37:54.000Z', 'text': '100点満点の神ホテルです😇'}, {'created_at': '2019-01-17T00:07:42.000Z', 'text': 'ロールスクリーンは完全な遮蔽にはなりません。室内の照明を点けると外から薄っすら透けて見えてしまいます。'}, {'created_at': '2019-01-17T00:07:15.000Z', 'text': '清潔感のある室内には3口の電源コンセントがあり、USB変換ACアダプタとスマホ用ケーブル（3分岐：USB Type C、USB Micro-B、Lightningコネクタ）も置かれていて非常に便利です。そのほかVOD見放題のTV、無料のペットボトルの水、鏡もついてます。'}, {'created_at': '2016-12-08T05:52:17.000Z', 'text': '夜行バスを降りた後やイベント後等にお風呂だけでも利用しやすいです'}, {'created_at': '2016-11-24T09:41:36.000Z', 'text': 'カプセルホテルとは思えない位にサービスが充実しています。JR秋葉原駅からも近くアクセスも良好。'}]"

In [ ]:
data['tastes'].unique()

array(["['hotel', 'cozy']",
       "['friendly staff', 'scenic views', 'hotel', 'buffet', 'luxury', 'modern rooms', 'Japanese breakfast', 'top floor']",
       "['saunas', 'open-air bath', 'cold-water bath']", nan,
       "['bath houses']",
       "['beer', 'breakfast food', 'wifi', 'massage', 'spa', 'resorts', 'saunas', 'hot springs', 'fireworks']",
       "['hotel', 'spa']",
       "['hotel', 'wifi', 'rice', 'park', 'lounges', 'spacious', 'spacious rooms']",
       "['breakfast food', 'sunsets', 'hotel', 'clean', 'croissants']",
       "['hotel', 'clean', 'bread', 'cozy', 'comfortable']",
       "['parking', 'quiet', 'soba', 'saunas', 'hot springs', 'bath houses', 'open-air bath']",
       "['hotel', 'bath houses']",
       "['Asian food', 'breakfast food', 'scenic views', 'hotel', 'cake', 'tea', 'rice', 'quiet', 'airports', 'buffet', 'malls', 'bus', 'lounges', '24-hour', 'cigars', 'beer gardens', 'halloween', 'fitness club']",
       "['friendly staff', 'breakfast food', 'hotel', 'wifi', 'rice', 'all you can eat', 'buffet', 'lounges', 'baseball', 'night view']",
       "['hot springs', 'bedrock bath']",
       "['alcohol', 'coffee', 'good service', 'breakfast food', 'Japanese food', 'scenic views', 'hotel', 'lunch', 'cake', 'rice', 'lounges', 'comfortable rooms', 'spacious rooms', 'teppanyaki', 'Japanese gardens', '40th floor']",
       "['Asian food']", "['coffee', 'breakfast food', 'hotel', 'juice']",
       "['beer', 'scenic views', 'massage', 'spa', 'saunas', 'bath houses', 'carbonated spring', 'cold-water bath']",
       "['scenic views', 'hotel', 'cake', 'bread']", "['hotel']",
       "['friendly staff', 'breakfast food', 'hotel', 'whiskey', 'swimming pool']",
       "['coffee', 'café', 'rice', 'crowded', 'saunas', 'hot springs', 'massage chairs', 'hammocks', 'manga']",
       "['breakfast food', 'hotel', 'clean', 'restrooms', 'airports', 'comfortable', 'spacious']",
       "['alcohol', 'breakfast food', 'hotel', 'all you can eat']",
       "['hotel', 'clean', 'airports', 'comfortable']",
       "['friendly staff', 'breakfast food', 'hotel', 'clean', 'wifi', 'quiet', 'airports', 'comfortable', 'pillows']",
       "['wifi']",
       "['scenic views', 'hotel', 'rice', 'all you can eat', 'knowledgeable staff']",
       "['breakfast food', 'hotel', 'airports', 'tapas', 'fresh fish', 'shuttle bus']",
       "['good service', 'breakfast food', 'hotel', 'lunch', 'beer gardens', 'lawson']",
       "['beer', 'fountains', 'hot springs']",
       "['hotel', 'rice', 'all you can eat', 'night view']",
       "['clean', 'wifi']", "['saunas']"], dtype=object)

In [ ]:
data['rating'].describe()

count    95.000000
mean      0.989876
std       0.008244
min       0.960615
25%       0.986761
50%       0.992585
75%       0.995197
max       0.998533
Name: popularity, dtype: float64

In [ ]:
data['rating'].describe()

count    67.000000
mean      7.780597
std       0.790711
min       6.100000
25%       7.250000
50%       7.900000
75%       8.300000
max       9.400000
Name: rating, dtype: float64

In [ ]:
data[data['rating'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,related_places_children,popularity,rating,tastes,tips,verified,website,hours_display,hours_is_local_holiday,hours_open_now,hours_regular,hours_seasonal,social_media_facebook_id,social_media_twitter,social_media_instagram,price
67,67,4c401b8eaf052d7f8c527b79,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],545,/v3/places/4c401b8eaf052d7f8c527b79,Korean YMCA Asia Youth Center in Japan (YMCAアジ...,Asia/Tokyo,35.700045,139.758409,猿楽町2丁目5-5,"猿楽町2丁目5-5, 千代田区, Tokyo, 101-0064",Chiyoda,101-0064,Tokyo,"[{'fsq_id': '526381a7498e22281e6c198a', 'name'...",0.994316,NaN,NaN,"[{'created_at': '2013-10-20T07:06:00.000Z', 't...",False,http://www.ymcajapan.org/ayc,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
68,68,5d4a6f51b2eb7b0008473c17,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],2962,/v3/places/5d4a6f51b2eb7b0008473c17,THE BLOSSOM HIBIYA,Asia/Tokyo,35.668996,139.756414,新橋1丁目1-13,"新橋1丁目1-13, 港区, Tokyo, 105-0004",Tokyo,105-0004,Tokyo,"[{'fsq_id': '5dec1feedf2c9e00081c34c9', 'name'...",0.987333,NaN,NaN,"[{'created_at': '2020-01-29T06:01:11.000Z', 't...",False,https://www.jrk-hotels.co.jp/Hibiya/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
69,69,5f6861060bfd233db3a6d086,"[{'id': 19009, 'name': 'Lodging', 'icon': {'pr...",[],3643,/v3/places/5f6861060bfd233db3a6d086,The Tokyo Edition Toranomon (東京エディション虎ノ門),Asia/Tokyo,35.665172,139.745421,虎ノ門4丁目1-1,"虎ノ門4丁目1-1, 港区, Tokyo, 105-0001",Minato,105-0001,Tokyo,"[{'fsq_id': '5f7c6760ee0b6a51b2113d14', 'name'...",0.995715,NaN,NaN,[],False,https://www.marriott.com/hotels/travel/TYOET-t...,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,NaN,NaN,NaN
70,70,5e368c17e5bac40007a6b735,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],4789,/v3/places/5e368c17e5bac40007a6b735,Sotetsu Fresa Inn (相鉄フレッサイン),Asia/Tokyo,35.698489,139.707860,新宿7丁目27-9,"新宿7丁目27-9, 新宿区, Tokyo, 160-0022",Shinjuku,160-0022,Tokyo,"[{'fsq_id': '4ba85cb1f964a52014d839e3', 'name'...",0.986838,NaN,NaN,[],False,https://fresa-inn.jp/higashishinjuku/,NaN,False,False,NaN,[],2.414758e+14,NaN,NaN,NaN
71,71,4ba8ce17f964a52058f039e3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],4990,/v3/places/4ba8ce17f964a52058f039e3,カプセルイン大塚,Asia/Tokyo,35.732522,139.728959,北大塚2丁目15-10,"北大塚2丁目15-10, 豊島区, Tokyo, 170-0004",Tokyo,170-0004,Tokyo,NaN,0.990422,NaN,NaN,"[{'created_at': '2021-08-01T09:13:23.000Z', 't...",False,http://www.capsule-in-otsuka.co.jp,NaN,False,False,NaN,[],NaN,capsuleinotsuka,NaN,NaN
72,72,5decf9691a58910008344e01,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],5874,/v3/places/5decf9691a58910008344e01,Hotel JAL City Tokyo Toyosu (ホテルJALシティ東京豊洲),Asia/Tokyo,35.647260,139.786859,豊洲6丁目4-20,"豊洲6丁目4-20 (Dタワー豊洲), 江東区, Tokyo, 135-0061",Kōtō,135-0061,Tokyo,"[{'fsq_id': '5decfb29e65f3d000787b6b0', 'name'...",0.996012,NaN,NaN,"[{'created_at': '2021-12-12T09:03:44.000Z', 't...",False,https://www.tokyo-toyosu.hoteljalcity.com,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
73,73,5973564defa82a569354eefd,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],6642,/v3/places/5973564defa82a569354eefd,Hotel Livemax (ホテルリブマックス東京潮見駅前),Asia/Tokyo,35.658309,139.818385,潮見2丁目8-8,"潮見2丁目8-8, 江東区, Tokyo, 135-0052",Kōtō,135-0052,Tokyo,NaN,0.975604,NaN,NaN,[],False,https://www.hotel-livemax.com/tokyo/shiomist/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
74,74,5f1b93f067564371a9124bcd,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],7000,/v3/places/5f1b93f067564371a9124bcd,Hotel Villa Fontaine Grand Tokyo Ariake (ホテルヴィ...,Asia/Tokyo,35.637568,139.791471,有明2丁目1-5,"有明2丁目1-5, 江東区, Tokyo, 135-0063",Tokyo,135-0063,Tokyo,"[{'fsq_id': '5f4ad97ba3787b2ae949aebc', 'name'...",0.995085,NaN,NaN,"[{'created_at': '2021-12-26T06:33:35.000Z', 't...",False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
75,75,5c6d7da3033693002cc898e9,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],7172,/v3/places/5c6d7da3033693002cc898e9,Miyako City Tokyo Takanawa (都シティ 東京高輪),Asia/Tokyo,35.633532,139.737758,高輪3丁目19-17,"高輪3丁目19-17, 港区, Tokyo, 108-0074",Tokyo,108-0074,Tokyo,NaN,0.994977,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
76,76,5d76e76503766000083b27c7,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],7490,/v3/places/5d76e76503766000083b27c7,Sotetsu Grand Fresa (相鉄グランドフレッサ 東京ベイ有明),Asia/Tokyo,35.632146,139.789667,有明 3丁目6-6,"有明 3丁目6-6, 江東区, Tokyo, 135-0063",Tokyo,135-0063,Tokyo,"[{'fsq_id': '5f3372c8d0ad182025bc6675', 'name'...",0.996634,NaN,NaN,"[{'created_at': '2019-11-17T21:10:37.000Z', 't...",False,https://fresa-inn.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,NaN,NaN,NaN
77,77,4d0007bfba1da1cd555c8628,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],11781,/v3/places/4d0007bfba1da1cd555c8628,Tokyo Inn (東京イン),Asia/Tokyo,35.597316,139.711790,北馬込2丁目31-6,"北馬込2丁目31-6, 大田区, Tokyo, 143-0021",Ōta,143-0021,Tokyo,"[{'fsq_id': '4b6398bff964a520cb852ae3', 'name'...",0.991128,NaN,NaN,"[{'created_at': '2014-08-09T00:36:00.000Z', 't...",False,http://www.tokyo-inn.co.jp/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
78,78,5efc852c25dda600087ed372,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],12555,/v3/places/5efc852c25dda600087ed372,グランドニッコー東京ベイ 舞浜,Asia/Tokyo,35.629322,139.873608,舞浜1-7,"舞浜1-7, 浦安市, Chiba, 279-0031",Urayasu,279-0031,Chiba,"[{'fsq_id': '5f6e9629deb4410a282a450a', 'name'...",0.986045,NaN,NaN,[],False,https://tokyobay.grandnikko.com,NaN,False,False,NaN,[],1.025498e+14,0701gntbm,grandnikkotokyobaymaihama,NaN
79,79,4c9db7d30df79c742980191a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],15301,/v3/places/4c9db7d30df79c742980191a,川崎グリーンプラザホテル,Asia/Tokyo,35.582561,139.663596,中原区丸子通1-653,"中原区丸子通1-653, 川崎市, Kanagawa, 211-0006",Kawasaki,211-0006,Kanagawa,"[{'fsq_id': '4c67569be75ac928a084fada', 'name'...",0.963858,NaN,NaN,"[{'created_at': '2015-07-04T10:39:01.000Z', 't...",False,http://www.greenplazahotel.co.jp/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
80,80,4de9f7ccb3ad083a33c2d34c,"[{'id': 16021, 'name': 'Hot Spring', 'icon': {...",[],19446,/v3/places/4de9f7ccb3ad083a33c2d34c,カプセル&サウナ 川崎ビッグ,Asia/Tokyo,35.527734,139.699793,川崎区小川町15-11,"川崎区小川町15-11, 川崎市, Kanagawa, 210-0023",Kawasaki,210-0023,Kanagawa,NaN,0.983706,NaN,['saunas'],"[{'created_at': '2022-03-05T22:17:34.000Z', 't...",False,http://www.kawasaki-big.com/,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,NaN,NaN,NaN
81,81,4bdf8bdb6316d13a26dba011,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],19475,/v3/places/4bdf8bdb6316d13a26dba011,ホテルメッツ武蔵境,Asia/Tokyo,35.701822,139.545230,境南町2丁目1-8,"境南町2丁目1-8, 武蔵野市, Tokyo, 180-0023",Musashino,180-0023,Tokyo,"[{'fsq_id': '4b871842f964a5204eb031e3', 'name'...",0.991645,NaN,NaN,"[{'created_at': '2011-09-09T23:27:11.000Z', 't...",False,https://www.hotelmets.jp/musashisakai/,Open Daily 6:30-22:30,False,False,"[{'close': '2230', 'day': 1, 'open': '0630'}, ...",[],NaN,NaN,NaN,NaN
82,82,4f17afc0e4b0f1e7baa2d8c8,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],22519,/v3/places/4f17afc0e4b0f1e7baa2d8c8,ステーションホテルチャボ,Asia/Tokyo,35.642147,139.520120,矢野口266-6,"矢野口266-6, 稲城市, Tokyo, 206-0812",Inagi-shi,206-0812,Tokyo,NaN,0.986314,NaN,NaN,[],False,http://www.st-hotel-chabo.jp,NaN,False,False,NaN,[],6.932594e+14,NaN,NaN,NaN
83,83,5d5650f0eb01dc00074a0e19,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],26294,/v3/places/5d5650f0eb01dc00074a0e19,カンデオホテルズ 大宮,Asia/Tokyo,35.903200,139.621493,大宮区桜木町1丁目401-1,"大宮区桜木町1丁目401-1, さいたま市, Saitama, 330-0854",Saitama-shi,330-0854,Saitama,"[{'fsq_id': '60b30b6b7b831004cd45d858', 'name'...",0.983311,NaN,NaN,"[{'created_at': '2022-03-16T12:49:41.000Z', 't...",False,http://www.candeohotels.com/omiya/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
84,84,4ba2ae78f964a5209b0f38e3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],26327,/v3/places/4ba2ae78f964a5209b0f38e3,クロス・ウェーブ府中,Asia/Tokyo,35.677539,139.469819,日鋼町1-40,"日鋼町1-40, 府中市, Tokyo, 183-0044",Fuchu,183-0044,Tokyo,NaN,0.978692,NaN,NaN,"[{'created_at': '2020-02-02T14:25:04.000Z', 't...",False,http://x-wave.orix.co.jp/fuchu/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
85,85,57276b57498e7b86c5ae1e11,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],27774,/v3/places/57276b57498e7b86c5ae1e11,The Bed and Spa (ザ ベッド アンド スパ),Asia/Tokyo,35.785778,139.473709,くすのき台1丁目13-1,"くすのき台1丁目13-1 (ガーデンシティ所沢 3F-4F), 所沢市, Saitama, ...",Tokorozawa,359-0037,Saitama,NaN,0.994848,NaN,NaN,"[{'created_at': '2020-09-18T22:31:56.000Z', 't...",False,http://bed-spa.jp,Open Daily 00:00-23:59,False,True,"[{'close': '2359', 'day': 1, 'open': '0000'}, ...",[],NaN,bedandspa,bed_spa.tokorozawa,NaN
86,86,5f94b53ee85b1932a4cac151,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],28116,/v3/places/5f94b53ee85b1932a4cac151,Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口),Asia/Tokyo,35.467834,139.624715,神奈川区金港町5-10,"神奈川区金港町5-10, 横浜市, Kanagawa, 221-0056",Yokohama,221-0056,Kanagawa,"[{'fsq_id': '5f9404f763d29f09153af8c8', 'name'...",0.988519,NaN,NaN,[],False,https://fresa-inn.jp/yokohama-higashiguchi/,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
87,87,603840c1ab44fd74e644ece8,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],28548,/v3/places/603840c1ab44fd74e644ece8,カプセルプラス横浜,Asia/Tokyo,35.466405,139.617794,西区北幸2丁目1-5,"西区北幸2丁目1-5, 横浜市, Kanagawa, 220-0004",Yokohama,220-0004,Kanagawa,NaN,0.995191,NaN,NaN,"[{'created_at': '2021-05-19T13:08:15.000Z', 't...",False,https://capsule-plus.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
88,88,5ed8f20aa93f0c0008001e5d,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],28869,/v3/places/5ed8f20aa93f0c0008001e5d,Yokohama Tokyu Rei Hotel (横浜東急REIホテル),Asia/Tokyo,35.459946,139.625860,西区みなとみらい4丁目3-6,"西区みなとみらい4丁目3-6, 横浜市, Kanagawa, 220-0012",Yokohama,220-0012,Kanagawa,"[{'fsq_id': '5efd2543fe54d70007b21a35', 'name'...",0.991413,NaN,NaN,"[{'created_at': '2020-12-28T07:54:10.000Z', 't...",False,https://www.tokyuhotels.co.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
89,89,4b763cfff964a520a9442ee3,"[{'id': 19009, 'name': 'Lodging', 'icon': {'pr...",[],28915,/v3/places/4b763cfff964a520a9442ee3,Queen's Tower (クイーンズタワー),Asia/Tokyo,35.457075,139.634108,西区みなとみらい2丁目3,"西区みなとみらい2丁目3, 横浜市, Kanagawa, 220-6090",Yokohama,220-6090,Kanagawa,"[{'fsq_id': '59e99213c4df1d5067955ceb', 'name'...",0.998228,NaN,NaN,"[{'created_at': '2011-07-27T00:23:15.000Z', 't...",False,http://www.qsy-tqc.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
90,90,6021eac0dc86d61c512b9d92,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],31759,/v3/places/6021eac0dc86d61c512b9d92,LINK FOREST,Asia/Tokyo,35.619700,139.421640,鶴牧3丁目5-3,"鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034",Tama,206-0034,Tokyo,"[{'fsq_id': '5df6c50db66e960008bf5b50', 'name'...",0.992253,NaN,NaN,"[{'created_at': '2021-03-25T23:26:29.000Z', 't...",False,https://link-forest.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
91,91,513805a1e4b032c75badf416,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],34743,/v3/places/513805a1e4b032c75badf416,ホテルココアミルク,Asia/Tokyo,36.006641,139.788515,立野276-1,"立野276-1, 春日部市, Saitama, 344-0134",Kasukabe,344-0134,Saitama,NaN,0.983966,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
92,92,4dd0e28452b1f8915bd0e895,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],41385,/v3/places/4dd0e28452b1f8915bd0e895,ホテルルートイン水海道駅前,Asia/Tokyo,36.017496,139.991883,水海道宝町1555-2,"水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023",Jōsō-shi,303-0023,Ibaraki,NaN,0.991480,NaN,NaN,[],False,http://www.route-inn.co.jp/search/hotel/index....,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
93,93,4c5d77ad94fd0f470665cb45,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",[],65615,/v3/places/4c5d77ad94fd0f470665cb45,ホテルシティーフィールドかごはら,Asia/Tokyo,36.173067,139.331743,籠原南1-123,"籠原南1-123, 熊谷市, Saitama, 360-0847",Kumagaya,360-0847,Saitama,NaN,0.960615,NaN,NaN,"[{'created_at': '2019-06-01T13:30:49.000Z', 't...",False,http://www.hotel-cityfield.co.jp,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN
94,94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",[],88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,Asia/Tokyo,35.818861,140.724906,太田129-23,"太田129-23, 神栖市, Ibaraki, 314-0254",Kamisu,314-0254,Ibaraki,NaN,0.990899,NaN,NaN,[],False,NaN,NaN,False,False,NaN,[],NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   fsq_id                      95 non-null     object
 1   categories                  95 non-null     object
 2   distance                    95 non-null     int64
 3   link                        95 non-null     object
 4   name                        95 non-null     object
 5   geocodes_main_latitude      95 non-null     float64
 6   geocodes_main_longitude     95 non-null     float64
 7   location_address            95 non-null     object
 8   location_formatted_address  95 non-null     object
 9   location_locality           95 non-null     object
 10  location_postcode           95 non-null     object
 11  location_region             95 non-null     object
 12  popularity                  95 non-null     float64
 13  rating                      67 non-null     float64
 14  tastes                      35 non-null     object
 15  tips                        95 non-null     object
dtypes: float64(4), int64(1), object(11)
memory usage: 12.0+ KB

In [ ]:
data.drop(columns=['Unnamed: 0', 'chains', 'timezone', 'related_places_children', 'verified', 'website', 'hours_display', 'hours_is_local_holiday', 'hours_open_now', 
      'hours_regular', 'hours_seasonal', 'social_media_facebook_id',
      'social_media_twitter', 'social_media_instagram', 'price'],inplace=True)

In [ ]:
data.columns

Index(['fsq_id', 'categories', 'distance', 'link', 'name',
       'geocodes_main_latitude', 'geocodes_main_longitude', 'location_address',
       'location_formatted_address', 'location_locality', 'location_postcode',
       'location_region', 'popularity', 'rating', 'tastes', 'tips'],
      dtype='object')

In [ ]:
data.head(1)

,fsq_id,categories,distance,link,name,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,popularity,rating,tastes,tips
0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't..."

In [ ]:
data.shape

(95, 16)

### Drop useless columns from 'brasil'

In [ ]:
pd.DataFrame(brasil.isnull().sum()).T

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
0,0,0,0,0,0,0,0,0,0,0,17,17,0,0,51,0,0,0,0,83,40,40,0,0,0,0,0,90,20,55,52,0,0,0,60,82,77,77,94,85,81,91

In [ ]:
brasil['social_media_facebook_id']

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
          ...
93             NaN
94             NaN
95             NaN
96    2.599924e+14
97             NaN
Name: social_media_facebook_id, Length: 98, dtype: float64

In [ ]:
brasil['rating'].isnull().sum()

82

In [ ]:
brasil[~brasil['tastes'].isnull()]

,Unnamed: 0,fsq_id,categories,chains,distance,link,name,timezone,geocodes_main_latitude,geocodes_main_longitude,geocodes_roof_latitude,geocodes_roof_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,location_neighborhood,popularity,price,tips,verified,hours_is_local_holiday,hours_open_now,hours_seasonal,social_media_twitter,website,hours_display,hours_regular,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,related_places_parent_fsq_id,related_places_parent_name,description,tastes,social_media_facebook_id,social_media_instagram
6,6,4bd574a94e32d13a20d0c080,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],627.0,/v3/places/4bd574a94e32d13a20d0c080,BARBACOA CLASSICO,Asia/Tokyo,35.682508,139.763913,35.682508,139.763913,丸の内1丁目5-1,JP,新丸ビル 6F,"丸の内1丁目5-1 (新丸ビル 6F), 千代田区, Tokyo, 100-6506",Chiyoda,100-6506,Tokyo,NaN,0.982706,2.0,"[{'created_at': '2020-08-09T05:55:48.000Z', 't...",True,False,True,[],NaN,https://barbacoa.jp/marunouchi/,"Mon-Fri 11:00-15:00, 17:00-21:00; Sat-Sun 11:0...","[{'close': '1500', 'day': 1, 'open': '1100'}, ...",Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,35.679206,139.769727,NaN,8.4,4b0587a6f964a520499e22e3,SPINDLE新丸の内ビルディング店,丸の内店,"['lunch', 'steak', 'cozy', 'great value', 'aut...",1.523837e+14,NaN
21,21,535a620411d212a99bebe77b,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],287.0,/v3/places/535a620411d212a99bebe77b,RIO GRANDE GRILL 横浜ベイクォーター,Asia/Tokyo,35.466282,139.626928,35.466282,139.626928,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa,NaN,0.954174,2.0,"[{'created_at': '2020-01-05T08:16:44.000Z', 't...",False,False,True,[],riograndegrill1,http://riogrande.createrestaurants.com/jp/inde...,"Mon-Fri 11:00-14:00, 17:00-22:00; Sat-Sun 11:0...","[{'close': '1400', 'day': 1, 'open': '1100'}, ...",スカイスパYOKOHAMA,35.464584,139.624648,横浜ベイクォーター3F エリア: 横浜駅,7.5,4b1b455df964a52067fa23e3,アロハテーブル Aloha Table 横浜ベイクォーター,NaN,"['lunch', 'good for working', 'cozy', 'good fo...",2.599924e+14,riograndegrill_official
31,31,4e6c86f91495f34925932762,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],390.0,/v3/places/4e6c86f91495f34925932762,BACANA GINZA (バッカーナ 銀座),Asia/Tokyo,35.668617,139.761883,35.668617,139.761883,銀座8丁目8-1,JP,出雲ビル B1F,"銀座8丁目8-1 (出雲ビル B1F), 中央区, Tokyo, 104-0061",Tokyo,104-0061,Tokyo,['Ginza / Tokyo Nihonbashi'],0.914322,2.0,"[{'created_at': '2018-07-12T11:29:54.000Z', 't...",False,False,True,[],bacanaginza,http://bacana-ginza.jimdo.com/,"Mon-Fri 11:30-15:00, 17:30-23:00; Sat 12:00-16...","[{'close': '1500', 'day': 1, 'open': '1130'}, ...",Sotetsu Fresa Inn Shimbashi-Hibiyaguchi (相鉄フレッ...,35.668182,139.757611,第7セントラルビルB1F,7.2,NaN,NaN,NaN,"['friendly staff', 'all you can eat', 'crowded...",NaN,NaN
40,40,528af03311d281c7eee110d4,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],724.0,/v3/places/528af03311d281c7eee110d4,"Barbacoa, Shibuya",Asia/Tokyo,35.661043,139.700333,35.661043,139.700333,宇田川町20-15,JP,ヒューマックスパビリオン渋谷公園通り 7F,"宇田川町20-15 (ヒューマックスパビリオン渋谷公園通り 7F), 渋谷区, Tokyo,...",Tokyo,150-0042,Tokyo,NaN,0.932480,2.0,"[{'created_at': '2018-11-09T03:23:58.000Z', 't...",True,False,True,[],NaN,https://barbacoa.jp/shibuya/,"Mon-Fri 11:30-15:00, 17:30-21:00; Sat-Sun 11:0...","[{'close': '1500', 'day': 1, 'open': '1130'}, ...",APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,8.5,NaN,NaN,渋谷店,"['all you can eat', 'pineapple', 'churrasco', ...",3.087339e+14,NaN
41,41,53c0fa87498e6127c41f69b1,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],395.0,/v3/places/53c0fa87498e6127c41f69b1,Gocchi Batta,Asia/Tokyo,35.658529,139.698268,35.658529,139.698268,道玄坂2丁目8-1,JP,大和田ビル 2F,"道玄坂2丁目8-1 (大和田ビル 2F), 渋谷区, Tokyo, 150-0043",Tokyo,150-0043,Tokyo,NaN,0.829161,2.0,"[{'created_at': '2020-12-16T00:50:04.000Z', 't...",False,False,False,[],NaN,http://kidshd.co.jp/,NaN,NaN,APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,6.7,NaN,NaN,NaN,"['beer', 'all you can eat', 'churrasco']",NaN,NaN
62,62,55530f91498eca9bfbb5737b,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],123.0,/v3/places/55530f91498eca9bfbb5737b,"Barbacoa, Takanawa",Asia/Tokyo,35.628417,139.736904,35.628417,139.736904,高輪4丁目10-18,JP,ウィング高輪WEST 3F,"高輪4丁目10-18 (ウィング高輪WEST 3F), 港区, Tokyo, 108-0074",Tokyo,108-0074,Tokyo,"['高輪, 東京, 東京都']",0.931548,2.0,"[{'created_at': '2019-09-29T21:55:26.000Z', 't...",True,False,True,[],NaN,https://barbacoa.jp/takanawa/,"Mon-Fri 11:00-15:00, 17:30-21:00; Sat-Sun 11:0...","[{'close': '1500', 'day': 1, 'open': '1100'}, ...",Annex Tower (アネックスタワー),35.627922,139.735793,NaN,8.8,4b512e45f964a520464627e3,ウィング高輪 WEST,高輪店,"['steak', 'crowded', 'authentic', 'fancy', 'ch...",1.613688e+15,NaN
64,64,4c3fcb59520fa5930438c7ac,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],446.0,/v3/places/4c3fcb59520fa5930438c7ac,ブラジリアンレストラン シェーガ マイス,Asia/Tokyo,35.525328,139.700606,NaN,NaN,川崎区貝塚1丁目4-16,JP,ライオンズマンション川崎貝塚 1F,"川崎区貝塚1丁目4-16 (ライオンズマンション川崎貝塚 1F), 川崎市, Kanagaw...",Kawasaki,210-0014,Kanagawa,NaN,0.879006,2.0,"[{'created_at': '2018-04-13T15:42:03.000Z', 't...",False,False,True,[],NaN,https://www.chegamais.co,"Tue-Fri 17:30-23:00; Sat-Sun 12:00-15:00, 17:3...","[{'close': '2300', 'day': 2, 'open': '1730'}, ...",Rex Inn Kawasaki (レックスイン川崎),35.527671,139.696606,ライオンズマンション川崎貝塚1F,8.2,NaN,NaN,NaN,['churrasco'],3.119940e+14,NaN
68,68,4e478a17887781a619b9fd99,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],419.0,/v3/places/4e478a17887781a619b9fd99,Teco-Teco (レストラン TECO‐TECO),Asia/Tokyo,35.780246,140.315129,35.780246,140.315129,上町858-1,JP,NaN,"上町858-1, 成田市, Chiba, 286-0032",Narita-shi,286-0032,Chiba,['Narita'],0.816077,2.0,"[{'created_at': '2019-07-04T11:26:26.000Z', 't...",False,False,True,[],NaN,http://www.teco-teco.jp,"Tue-Sun 11:30-14:30, 17:30-22:30","[{'close': '1430', 'day': 2, 'open': '1130'}, ...",APA HOTEL Keisei Narita-Ekimae (アパホテル 京成成田駅前),35.776691,140.316779,NaN,8.7,NaN,NaN,NaN,"['healthy food', 'cozy', 'authentic', 'fancy',...",2.590880e+14,NaN
74,74,4e6c86f91495f34925932762,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],492.0,/v3/places/4e6c86f91495f34925932762,BACANA GINZA (バッカーナ 銀座),Asia/Tokyo,35.668617,139.761883,35.668617,139.761883,銀座8丁目8-1,JP,出雲ビル B1F,"銀座8丁目8-1 (出雲ビル B1F), 中央区, Tokyo, 104-0061",Tokyo,104-0061,Tokyo,['Ginza / Tokyo Nihonbashi'],0.914322,2.0,"[{'created_at': '2018-07-12T11:29:54.000Z', 't...",False,False,True,[],bacanaginza,http://bacana-ginza.jimdo.com/,"Mon-Fri 11:30-15:00, 17:30-23:00; Sat 12:00-16...","[{'close': '1500', 'day': 1, 'open': '1130'}, ...",THE BLOSSOM HIBIYA,35.668996,139.756414,第7セントラルビルB1F,7.2,NaN,NaN,NaN,"['friendly staff', 'all you can eat', 'crowded...",NaN,NaN
85,85,55530f91498eca9bfbb5737b,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],562.0,/v3/places/55530f91498eca9bfbb5737b,"Barbacoa, Takanawa",Asia/Tokyo,35.628417,139.736904,35.628417,139.736904,高輪4丁目10-18,JP,ウィング高輪WEST 3F,"高輪4丁目10-18 (ウィング高輪WEST 3F), 港区, Tokyo, 108-0074",Tokyo,108-0074,Tokyo,"['高輪, 東京, 東京都']",0.931548,2.0,"[{'created_at': '2019-09-29T21:55:26.000Z', 't...",True,False,True,[],NaN,https://barbacoa.jp/takanawa/,"Mon-Fri 11:00-15:00, 17:30-21:00; Sat-Sun 11:0...","[{'close': '1500', 'day': 1, 'open': '1100'}, ...",Miyako City Tokyo Takanawa (都シティ 東京高輪),35.633532,139.737758,NaN,8.8,4b512e45f964a520464627e3,ウィング高輪 WEST,高輪店,"['steak', 'crowded', 'authentic', 'fancy', 'ch...",1.613688e+15,NaN
89,89,4c3fcb59520fa5930438c7ac,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",[],270.0,/v3/places/4c3fcb59520fa5930438c7ac,ブラジリアンレストラン シェーガ マイス,Asia/Tokyo,35.525328,139.700606,NaN,NaN,川崎区貝塚1丁目4-16,JP,ライオンズマンション川崎貝塚 1F,"川崎区貝塚1丁目4-16 (ライオンズマンション川崎貝塚 1F), 川崎市, Kanagaw...",Kawasaki,210-0014,Kanagawa,NaN,0.879006,2.0,"[{'created_at': '2018-04-13T15:42:03.000Z', 't...",False,False,True,[],NaN,https://www.chegamais.co,"Tue-Fri 17:30-23:00; Sat-Sun 12:00-15:00, 17:3...","[{'close': '2300', 'day': 2, 'open': '1730'}, ...",カプセル&サウナ 川崎ビッグ,35.527734,139.699793,ライオンズマンション川崎貝塚1F,8.2,NaN,NaN,NaN,['churrasco'],3.119940e+14,NaN
91,91,535a620411d212a99bebe77b,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],295.0,/v3/places/535a620411d212a99bebe77b,RIO GRANDE GRILL 横浜ベイクォーター,Asia/Tokyo,35.466282,139.626928,35.466282,139.626928,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa,NaN,0.954174,2.0,"[{'created_at': '2020-01-05T08:16:44.000Z', 't...",False,False,True,[],riograndegrill1,http://riogrande.createrestaurants.com/jp/inde...,"Mon-Fri 11:00-14:00, 17:00-22:00; Sat-Sun 11:0...","[{'close': '1400', 'day': 1, 'open': '1100'}, ...",Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口),35.467834,139.624715,横浜ベイクォーター3F エリア: 横浜駅,7.5,4b1b455df964a52067fa23e3,アロハテーブル Aloha Table 横浜ベイクォーター,NaN,"['lunch', 'good for working', 'cozy', 'good fo...",2.599924e+14,riograndegrill_official
96,96,535a620411d212a99bebe77b,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",[],696.0,/v3/places/535a620411d212a99bebe77b,RIO GRANDE GRILL 横浜ベイクォーター,Asia/Tokyo,35.466282,139.626928,35.466282,139.626928,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa,NaN,0.954174,2.0,"[{'created_at': '2020-01-05T08:16:44.000Z', 't...",False,False,True,[],riograndegrill1,http://riogrande.createrestaurants.com/jp/inde...,"Mon-Fri 11:00-14:00, 17:00-22:00; Sat-Sun 11:0...","[{'close': '1400', 'day': 1, 'open': '1100'}, ...",Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター3F エリア: 横浜駅,7.5,4b1b455df964a52067fa23e3,アロハテーブル Aloha Table 横浜ベイクォーター,NaN,"['lunch', 'good for working', 'cozy', 'good fo...",2.599924e+14,riograndegrill_official

In [ ]:
brasil['hours_regular'].value_counts()

[{'close': '2300', 'day': 1, 'open': '1030'}, {'close': '2300', 'day': 2, 'open': '1030'}, {'close': '2300', 'day': 3, 'open': '1030'}, {'close': '2300', 'day': 4, 'open': '1030'}, {'close': '2300', 'day': 5, 'open': '1030'}, {'close': '2300', 'day': 6, 'open': '1030'}, {'close': '2300', 'day': 7, 'open': '1030'}]                                                                                                                                                                                                                                                                                                                               8
[{'close': '2300', 'day': 1, 'open': '1100'}, {'close': '2300', 'day': 2, 'open': '1100'}, {'close': '2300', 'day': 3, 'open': '1100'}, {'close': '2300', 'day': 4, 'open': '1100'}, {'close': '2300', 'day': 5, 'open': '1100'}, {'close': '2300', 'day': 6, 'open': '1100'}, {'close': '2300', 'day': 7, 'open': '1100'}]                                                                                                                                                                                                                                                                                                                               4
[{'close': '1500', 'day': 1, 'open': '1130'}, {'close': '2100', 'day': 1, 'open': '1730'}, {'close': '1500', 'day': 2, 'open': '1130'}, {'close': '2100', 'day': 2, 'open': '1730'}, {'close': '1500', 'day': 3, 'open': '1130'}, {'close': '2100', 'day': 3, 'open': '1730'}, {'close': '1500', 'day': 4, 'open': '1130'}, {'close': '2100', 'day': 4, 'open': '1730'}, {'close': '1500', 'day': 5, 'open': '1130'}, {'close': '2100', 'day': 5, 'open': '1730'}, {'close': '1600', 'day': 6, 'open': '1130'}, {'close': '2100', 'day': 6, 'open': '1700'}, {'close': '1600', 'day': 7, 'open': '1130'}, {'close': '2100', 'day': 7, 'open': '1700'}]    4
[{'close': '1400', 'day': 1, 'open': '1100'}, {'close': '2200', 'day': 1, 'open': '1700'}, {'close': '1400', 'day': 2, 'open': '1100'}, {'close': '2200', 'day': 2, 'open': '1700'}, {'close': '1400', 'day': 3, 'open': '1100'}, {'close': '2200', 'day': 3, 'open': '1700'}, {'close': '1400', 'day': 4, 'open': '1100'}, {'close': '2200', 'day': 4, 'open': '1700'}, {'close': '1400', 'day': 5, 'open': '1100'}, {'close': '2200', 'day': 5, 'open': '1700'}, {'close': '1500', 'day': 6, 'open': '1100'}, {'close': '2200', 'day': 6, 'open': '1600'}, {'close': '1500', 'day': 7, 'open': '1100'}, {'close': '2200', 'day': 7, 'open': '1600'}]    3
[{'close': '1500', 'day': 1, 'open': '1100'}, {'close': '2300', 'day': 1, 'open': '1700'}, {'close': '1500', 'day': 2, 'open': '1100'}, {'close': '2300', 'day': 2, 'open': '1700'}, {'close': '1500', 'day': 3, 'open': '1100'}, {'close': '2300', 'day': 3, 'open': '1700'}, {'close': '1500', 'day': 4, 'open': '1100'}, {'close': '2300', 'day': 4, 'open': '1700'}, {'close': '1500', 'day': 5, 'open': '1100'}, {'close': '2300', 'day': 5, 'open': '1700'}, {'close': '1500', 'day': 6, 'open': '1100'}, {'close': '2200', 'day': 6, 'open': '1700'}, {'close': '1500', 'day': 7, 'open': '1100'}, {'close': '2200', 'day': 7, 'open': '1700'}]    3
[{'close': '2100', 'day': 1, 'open': '1700'}, {'close': '2100', 'day': 2, 'open': '1700'}, {'close': '2100', 'day': 3, 'open': '1700'}, {'close': '2100', 'day': 4, 'open': '1700'}, {'close': '2100', 'day': 5, 'open': '1700'}, {'close': '1500', 'day': 6, 'open': '1200'}, {'close': '2100', 'day': 6, 'open': '1600'}, {'close': '1500', 'day': 7, 'open': '1200'}, {'close': '2100', 'day': 7, 'open': '1600'}]                                                                                                                                                                                                                                     3
[{'close': '1500', 'day': 1, 'open': '1130'}, {'close': '2300', 'day': 1, 'open': '1730'}, {'close': '1500', 'day': 2, 'open': '1130'}, {'close': '2300', 'day': 2, 'open': '1730'}, {'close': '1500', 'day': 3, 'open': '1130'}, {'close': '2300', 'day': 3, 'open': '1730'}, {'close': '1500', 'day': 4, 'open': '1130'}, {'close': '2300', 'day': 4, 'open': '1730'}, {'close': '1500', 'day': 5, 'open': '1130'}, {'close': '2300', 'day': 5, 'open': '1730'}, {'close': '1600', 'day': 6, 'open': '1200'}, {'close': '2300', 'day': 6, 'open': '1730'}, {'close': '1600', 'day': 7, 'open': '1200'}, {'close': '2200', 'day': 7, 'open': '1730'}]    2
[{'close': '1330', 'day': 1, 'open': '1200'}, {'close': '2100', 'day': 1, 'open': '1700'}, {'close': '1330', 'day': 2, 'open': '1200'}, {'close': '2100', 'day': 2, 'open': '1700'}, {'close': '1330', 'day': 3, 'open': '1200'}, {'close': '2100', 'day': 3, 'open': '1700'}, {'close': '1330', 'day': 4, 'open': '1200'}, {'close': '2100', 'day': 4, 'open': '1700'}, {'close': '1330', 'day': 5, 'open': '1200'}, {'close': '2100', 'day': 5, 'open': '1700'}, {'close': '1330', 'day': 6, 'open': '1200'}, {'close': '2100', 'day': 6, 'open': '1700'}, {'close': '1330', 'day': 7, 'open': '1200'}, {'close': '2100', 'day': 7, 'open': '1700'}]    2
[{'close': '1500', 'day': 1, 'open': '1130'}, {'close': '2230', 'day': 1, 'open': '1700'}, {'close': '1500', 'day': 2, 'open': '1130'}, {'close': '2230', 'day': 2, 'open': '1700'}, {'close': '1500', 'day': 3, 'open': '1130'}, {'close': '2230', 'day': 3, 'open': '1700'}, {'close': '1500', 'day': 4, 'open': '1130'}, {'close': '2230', 'day': 4, 'open': '1700'}, {'close': '1500', 'day': 5, 'open': '1130'}, {'close': '2230', 'day': 5, 'open': '1700'}, {'close': '2230', 'day': 6, 'open': '1700'}]                                                                                                                                           2
[{'close': '2359', 'day': 1, 'open': '1700'}, {'close': '0200', 'day': 2, 'open': '0000'}, {'close': '2359', 'day': 2, 'open': '1700'}, {'close': '0200', 'day': 3, 'open': '0000'}, {'close': '2359', 'day': 3, 'open': '1700'}, {'close': '0200', 'day': 4, 'open': '0000'}, {'close': '2359', 'day': 4, 'open': '1700'}, {'close': '0200', 'day': 5, 'open': '0000'}, {'close': '2359', 'day': 5, 'open': '1700'}, {'close': '0500', 'day': 6, 'open': '0000'}, {'close': '2359', 'day': 6, 'open': '1700'}, {'close': '0500', 'day': 7, 'open': '0000'}, {'close': '2359', 'day': 7, 'open': '1600'}]                                                 2
[{'close': '1500', 'day': 1, 'open': '1100'}, {'close': '2100', 'day': 1, 'open': '1730'}, {'close': '1500', 'day': 2, 'open': '1100'}, {'close': '2100', 'day': 2, 'open': '1730'}, {'close': '1500', 'day': 3, 'open': '1100'}, {'close': '2100', 'day': 3, 'open': '1730'}, {'close': '1500', 'day': 4, 'open': '1100'}, {'close': '2100', 'day': 4, 'open': '1730'}, {'close': '1500', 'day': 5, 'open': '1100'}, {'close': '2100', 'day': 5, 'open': '1730'}, {'close': '1600', 'day': 6, 'open': '1100'}, {'close': '2100', 'day': 6, 'open': '1700'}, {'close': '1600', 'day': 7, 'open': '1100'}, {'close': '2100', 'day': 7, 'open': '1700'}]    2
[{'close': '2300', 'day': 2, 'open': '1730'}, {'close': '2300', 'day': 3, 'open': '1730'}, {'close': '2300', 'day': 4, 'open': '1730'}, {'close': '2300', 'day': 5, 'open': '1730'}, {'close': '1500', 'day': 6, 'open': '1200'}, {'close': '2300', 'day': 6, 'open': '1730'}, {'close': '1500', 'day': 7, 'open': '1200'}, {'close': '2300', 'day': 7, 'open': '1730'}]                                                                                                                                                                                                                                                                                  2
[{'close': '1430', 'day': 2, 'open': '1130'}, {'close': '2230', 'day': 2, 'open': '1730'}, {'close': '1430', 'day': 3, 'open': '1130'}, {'close': '2230', 'day': 3, 'open': '1730'}, {'close': '1430', 'day': 4, 'open': '1130'}, {'close': '2230', 'day': 4, 'open': '1730'}, {'close': '1430', 'day': 5, 'open': '1130'}, {'close': '2230', 'day': 5, 'open': '1730'}, {'close': '1430', 'day': 6, 'open': '1130'}, {'close': '2230', 'day': 6, 'open': '1730'}, {'close': '1430', 'day': 7, 'open': '1130'}, {'close': '2230', 'day': 7, 'open': '1730'}]                                                                                              2
[{'close': '1500', 'day': 1, 'open': '1100'}, {'close': '2100', 'day': 1, 'open': '1700'}, {'close': '1500', 'day': 2, 'open': '1100'}, {'close': '2100', 'day': 2, 'open': '1700'}, {'close': '1500', 'day': 3, 'open': '1100'}, {'close': '2100', 'day': 3, 'open': '1700'}, {'close': '1500', 'day': 4, 'open': '1100'}, {'close': '2100', 'day': 4, 'open': '1700'}, {'close': '1500', 'day': 5, 'open': '1100'}, {'close': '2100', 'day': 5, 'open': '1700'}, {'close': '1600', 'day': 6, 'open': '1100'}, {'close': '2100', 'day': 6, 'open': '1700'}, {'close': '1600', 'day': 7, 'open': '1100'}, {'close': '2100', 'day': 7, 'open': '1700'}]    1
[{'close': '1400', 'day': 1, 'open': '1130'}, {'close': '2300', 'day': 1, 'open': '1700'}, {'close': '1400', 'day': 2, 'open': '1130'}, {'close': '2300', 'day': 2, 'open': '1700'}, {'close': '1400', 'day': 3, 'open': '1130'}, {'close': '2300', 'day': 3, 'open': '1700'}, {'close': '1400', 'day': 4, 'open': '1130'}, {'close': '2300', 'day': 4, 'open': '1700'}, {'close': '1400', 'day': 5, 'open': '1130'}, {'close': '2300', 'day': 5, 'open': '1700'}, {'close': '2300', 'day': 6, 'open': '1700'}, {'close': '2300', 'day': 7, 'open': '1700'}]                                                                                              1
[{'close': '1500', 'day': 1, 'open': '1130'}, {'close': '2100', 'day': 1, 'open': '1730'}, {'close': '1500', 'day': 2, 'open': '1130'}, {'close': '2100', 'day': 2, 'open': '1730'}, {'close': '1500', 'day': 3, 'open': '1130'}, {'close': '2100', 'day': 3, 'open': '1730'}, {'close': '1500', 'day': 4, 'open': '1130'}, {'close': '2100', 'day': 4, 'open': '1730'}, {'close': '1500', 'day': 5, 'open': '1130'}, {'close': '2100', 'day': 5, 'open': '1730'}, {'close': '1600', 'day': 6, 'open': '1100'}, {'close': '2100', 'day': 6, 'open': '1700'}, {'close': '1600', 'day': 7, 'open': '1100'}, {'close': '2100', 'day': 7, 'open': '1700'}]    1
[{'close': '2359', 'day': 1, 'open': '1200'}, {'close': '2359', 'day': 2, 'open': '1200'}, {'close': '2359', 'day': 3, 'open': '1200'}, {'close': '2359', 'day': 4, 'open': '1200'}, {'close': '2359', 'day': 5, 'open': '1200'}, {'close': '0400', 'day': 6, 'open': '0000'}, {'close': '2359', 'day': 6, 'open': '1200'}, {'close': '0400', 'day': 7, 'open': '0000'}, {'close': '2359', 'day': 7, 'open': '1200'}]                                                                                                                                                                                                                                     1
[{'close': '1430', 'day': 1, 'open': '1200'}, {'close': '2100', 'day': 1, 'open': '1730'}, {'close': '1430', 'day': 2, 'open': '1200'}, {'close': '2100', 'day': 2, 'open': '1730'}, {'close': '1430', 'day': 3, 'open': '1200'}, {'close': '2100', 'day': 3, 'open': '1730'}, {'close': '1430', 'day': 4, 'open': '1200'}, {'close': '2100', 'day': 4, 'open': '1730'}, {'close': '1430', 'day': 5, 'open': '1200'}, {'close': '2100', 'day': 5, 'open': '1730'}, {'close': '1400', 'day': 6, 'open': '1200'}, {'close': '2100', 'day': 6, 'open': '1700'}, {'close': '1400', 'day': 7, 'open': '1200'}, {'close': '2100', 'day': 7, 'open': '1700'}]    1
[{'close': '1400', 'day': 1, 'open': '1130'}, {'close': '2330', 'day': 1, 'open': '1700'}, {'close': '1400', 'day': 2, 'open': '1130'}, {'close': '2330', 'day': 2, 'open': '1700'}, {'close': '1400', 'day': 3, 'open': '1130'}, {'close': '2330', 'day': 3, 'open': '1700'}, {'close': '1400', 'day': 4, 'open': '1130'}, {'close': '2330', 'day': 4, 'open': '1700'}, {'close': '1400', 'day': 5, 'open': '1130'}, {'close': '2330', 'day': 5, 'open': '1700'}, {'close': '1400', 'day': 6, 'open': '1130'}, {'close': '2330', 'day': 6, 'open': '1700'}]                                                                                              1
[{'close': '2359', 'day': 1, 'open': '1800'}, {'close': '2359', 'day': 2, 'open': '1800'}, {'close': '2359', 'day': 3, 'open': '1800'}, {'close': '2359', 'day': 4, 'open': '1800'}, {'close': '2359', 'day': 5, 'open': '1800'}, {'close': '2359', 'day': 6, 'open': '1800'}, {'close': '2359', 'day': 7, 'open': '1800'}]                                                                                                                                                                                                                                                                                                                               1
Name: hours_regular, dtype: int64

In [ ]:
brasil['website']

0                                                   NaN
1                    http://www.pj-partners.com/tucano/
2                         http://www.pjgroup.jp/tucanos
3                             http://brasilicagrill.com
4                                http://www.la10.tokyo/
                            ...
93    http://riogrande.createrestaurants.com/jp/yoko...
94    https://www.cial.co.jp/yokohama/floorguide/det...
95    http://riogrande.createrestaurants.com/jp/yoko...
96    http://riogrande.createrestaurants.com/jp/inde...
97    http://riogrande.createrestaurants.com/jp/yoko...
Name: website, Length: 98, dtype: object

In [ ]:
brasil['tips'].

SyntaxError: ignored

In [ ]:
brasil['tips'].unique()

array(['[]',
       '[{\'created_at\': \'2016-12-19T16:23:29.000Z\', \'text\': \'クイックシュラスコ980円！ 色々食べられる\'}, {\'created_at\': \'2016-02-07T08:46:44.000Z\', \'text\': "One of the best churrascarias in Tokyo! Really recommend the Papaya Cream dessert, don\'t forget to ask for the cassis topping!!"}]',
       "[{'created_at': '2020-08-09T05:55:48.000Z', 'text': 'My 1000th place in Japan!'}, {'created_at': '2018-11-05T09:06:21.000Z', 'text': 'Souped up version of the original chain'}, {'created_at': '2016-02-02T02:51:30.000Z', 'text': 'Absolutely love this place, although it can be hard to get a reservation. Book well in advance!'}, {'created_at': '2016-01-01T09:40:33.000Z', 'text': 'a bit pricey'}, {'created_at': '2014-09-17T04:20:32.000Z', 'text': 'Honra o nome barbacoa. A carne estava excelente o o ponto perfeito.'}]",
       "[{'created_at': '2022-01-03T09:50:22.000Z', 'text': 'Churrasco e bilf'}, {'created_at': '2021-12-31T10:45:31.000Z', 'text': 'Salada 🥗 bar'}, {'created_at': '2019-11-02T11:31:40.000Z', 'text': 'A noite, no rodízio, as carnes estavam bem ok, não excelentes como se esperaria pelo preço. O destaque pra mim ficou no pão de queijo, no atendimento e no caipilé de maracujá.'}, {'created_at': '2018-03-21T11:44:17.000Z', 'text': 'A good number of the Male staff wouldn’t stop staring at, and making comments about, my girlfriend’s body. I cannot recommend such unprofessional and frankly creepy behaviour.'}]",
       "[{'created_at': '2018-12-08T04:46:32.000Z', 'text': '肩ロースのシュラスコ'}, {'created_at': '2018-10-12T03:05:13.000Z', 'text': 'ボリューム満点。コスパ良し👍'}]",
       "[{'created_at': '2020-01-05T08:16:44.000Z', 'text': 'サラダバー、選り取りの肉'}, {'created_at': '2017-06-17T06:16:18.000Z', 'text': 'Amazing food. Great cuts of perfectly cooked meat. So full. Delicious.'}, {'created_at': '2015-12-12T07:35:43.000Z', 'text': 'Great place and nice food and service, the meat just keeps coming'}, {'created_at': '2015-10-06T05:47:41.000Z', 'text': 'お昼はサラダバーでカレー、ミートボールとかあるのでそれだけで十分！そう考えるとかなり安い〜'}, {'created_at': '2014-12-14T11:39:31.000Z', 'text': '屋外テラスは寒いけど、いい雰囲気'}]",
       "[{'created_at': '2021-10-02T11:09:12.000Z', 'text': '肉も美味しいがそれ以外のサイドディッシュもどれも美味しい。'}, {'created_at': '2020-07-14T05:05:47.000Z', 'text': '肉がジューシー、スモーキー、フルーティー！'}]",
       "[{'created_at': '2012-05-18T14:44:04.000Z', 'text': '金曜日はライブあり。踊りあり。遊べます。'}, {'created_at': '2011-07-02T12:27:58.000Z', 'text': ''}]",
       "[{'created_at': '2018-07-12T11:29:54.000Z', 'text': 'memo:ランチ食べ放題。シュラスコ'}, {'created_at': '2016-12-09T14:57:13.000Z', 'text': 'Good food and very friendly staff'}, {'created_at': '2015-12-23T15:27:52.000Z', 'text': 'リーズナブルにシュラスコを楽しめる良いお店。肉の味は値段以上で期待を損なうことはないはず。まだ一回しか訪問していないが、昔の洋食屋のようなこじんまりとした店内に、節度あるフレンドリーさのスタッフで心地よく食事ができた。ただ肉のサーブはや偏りがあるため、食べたい物が決まっている場合はスタッフを呼んでお願いした方がベター。'}, {'created_at': '2015-08-08T06:32:45.000Z', 'text': '結構腹に溜まります。'}, {'created_at': '2015-02-01T06:06:36.000Z', 'text': 'フィレが一番美味しい！豚バラは油多いから量食べれない私はパスで。'}]",
       "[{'created_at': '2020-07-10T05:04:02.000Z', 'text': 'ミックス ランチ、牛ランプステーキ'}, {'created_at': '2018-11-19T06:05:43.000Z', 'text': 'ランチメニューはシュラスコ3点とサラダ等ビュッフェで1280円 追加料金でシュラスコ増やせます'}]",
       "[{'created_at': '2018-11-09T03:23:58.000Z', 'text': 'Absolutely fantastic meat and worth the money. Everything was top notch and the sala2d bar was premium quality. Totally reccomend this place.'}, {'created_at': '2017-04-03T23:12:09.000Z', 'text': '2時間制食べ放題のシュラスコのお店。5〜10分毎に店員さんが肉を持って現れる。サラダバーの種類が多く、けっこうおいしい。肉はもちろんおいしいし、種類もまあまあ。焼きパイナップルは口直しにおすすめ。'}, {'created_at': '2017-01-08T04:29:52.000Z', 'text': 'Ótimo churrasco! Legitimamente brasileiro na capital japonesa!'}, {'created_at': '2015-11-13T22:01:19.000Z', 'text': '肉なら断然こちら♬スタッフさんの対応も抜群‼︎'}, {'created_at': '2015-09-03T15:06:14.000Z', 'text': 'シュラスコ。おしゃれな店内。'}]",
       "[{'created_at': '2020-12-16T00:50:04.000Z', 'text': 'シュラスコの美味しいお店'}, {'created_at': '2018-02-23T15:51:29.000Z', 'text': 'Had more than enough meat and beer. More than satisfied.'}, {'created_at': '2016-08-15T21:59:53.000Z', 'text': 'シュラスコ食べ放題。サービスも適度な空気感があって素晴らしいです'}, {'created_at': '2016-04-23T10:10:16.000Z', 'text': 'ランチ2500円（土日祝、ソフトドリンクとサラダバーつき）。コスパがよい。店員さんも愛想がよくテキパキしていた。お肉の種類も満足。'}, {'created_at': '2015-06-22T06:18:46.000Z', 'text': '9種類の生ビールのほとんどがアサヒでプレミアムや黒も置いてあるので好きな方には大満足かと'}]",
       "[{'created_at': '2016-10-06T06:19:24.000Z', 'text': 'Music Bars and Cafes - http://www.timeout.com/tokyo/music/best-music-spots-in-tokyo'}]",
       "[{'created_at': '2014-05-13T12:30:01.000Z', 'text': 'シュラスコ食べ放題は、わりとゆっくりペースでサーブされます'}]",
       "[{'created_at': '2017-08-23T14:10:38.000Z', 'text': 'Not the best Brazilian food out there. The Guaraná is very watered down!'}]",
       "[{'created_at': '2019-09-29T21:55:26.000Z', 'text': 'Excellent steak house with great service.'}, {'created_at': '2019-05-25T05:20:53.000Z', 'text': '色々な部位のお肉、サラダバー、デザート、ドリンクバーが楽しめる。店員は外国人が多く、接客姿勢などを含め日本にいる気がしない'}, {'created_at': '2018-10-10T12:25:59.000Z', 'text': 'Everything is good! They bring various meat to your table. They don’t stop bringing food until you tell them by flipping the coin over to stop. I love the grilled pineapple. They also have a salad bar'}, {'created_at': '2018-03-18T05:42:38.000Z', 'text': 'ボリュームいっぱいで、串に刺さっている状態から切ってくれるピッカーニャ（イチボ）は最高。'}, {'created_at': '2017-03-07T07:29:00.000Z', 'text': 'ランチタイムは3600円で、シュラスコ食べ放題・サラダバー・ドリンクバー・デザートバー付き。平日は空いていてゆっくりと食事を楽しめます。最初に沢山サラダを食べて、あとは好きなお肉を食べ放題。お肉の部位が色々あるので、あまりがっつかずにゆっくりと食べるのがオススメです。'}]",
       "[{'created_at': '2018-04-13T15:42:03.000Z', 'text': 'パイナップルめちゃうま！'}, {'created_at': '2017-09-23T15:42:31.000Z', 'text': 'アラカルトも色々あります ライスには味が付いてて美味しい'}, {'created_at': '2016-08-26T13:33:08.000Z', 'text': 'シュラスコ食べ放題はほんの少し割高な気もするけど肉は美味い、そして分厚い。シナモンをふりかけた焼きパイナップルは別腹でいけるくらい美味。L.O.待たずにお腹いっぱい…笑'}, {'created_at': '2014-02-09T08:35:07.000Z', 'text': 'おそらく川崎では唯一のブラジルレストラン？？土日祝はシュハスコやってるということで行ってきました。うま〜い！！'}, {'created_at': '2012-04-13T03:49:25.000Z', 'text': 'シュラスコ食べ放題120分3250円は金、土、日、祝、のみ。平日のシュラスコは2日前までに予約が必要です。'}]",
       '[{\'created_at\': \'2019-07-04T11:26:26.000Z\', \'text\': "The food was good. Best I\'ve had outside of Brasil."}, {\'created_at\': \'2016-10-31T05:05:55.000Z\', \'text\': \'Great family run restaurant right in Narita. Crew set was wonderful.\'}, {\'created_at\': \'2015-05-25T08:29:28.000Z\', \'text\': \'Dinner in Japan\'}, {\'created_at\': \'2014-08-29T00:12:47.000Z\', \'text\': \'Muito bom!!!     👩  🙏\'}, {\'created_at\': \'2014-08-22T07:46:58.000Z\', \'text\': \'Todos os pratos são bons e bem servidos, mas o meu preferido é a costela assada, pra ser comida rezando, acompanha banana a milaneza, mandioca frita, lingüiça, arroz e feijão.\'}]'],
      dtype=object)

In [ ]:
brasil['tips'].isnull().sum()

0

In [ ]:
brasil['price'].unique()

array([ 2., nan])

In [ ]:
brasil['price'].isnull().sum()

40

In [ ]:
brasil.drop(columns=['Unnamed: 0', 'chains', 'timezone', 'geocodes_roof_latitude', 'geocodes_roof_longitude', 'location_neighborhood', 'price', 
                   'verified', 'hours_is_local_holiday', 'hours_open_now', 'hours_seasonal', 'social_media_twitter', 
                   'hours_display', 'hours_regular', 'related_places_parent_fsq_id', 'related_places_parent_name','description', 
                   'social_media_facebook_id', 'website', 'social_media_instagram'], inplace=True)

In [ ]:
data.columns

Index(['fsq_id', 'categories', 'distance', 'link', 'name',
       'geocodes_main_latitude', 'geocodes_main_longitude', 'location_address',
       'location_formatted_address', 'location_locality', 'location_postcode',
       'location_region', 'popularity', 'rating', 'tastes', 'tips'],
      dtype='object')

### Duplicatas dentro das colunas

In [ ]:
data.columns

Index(['fsq_id', 'categories', 'distance', 'link', 'name',
       'geocodes_main_latitude', 'geocodes_main_longitude', 'location_address',
       'location_formatted_address', 'location_locality', 'location_postcode',
       'location_region', 'popularity', 'rating', 'tastes', 'tips'],
      dtype='object')

In [ ]:
data['location_locality'].sort_values().unique().tolist()

['Akiruno',
 'Atami',
 'Chiba',
 'Chichibu',
 'Chiyoda',
 'Chuo',
 'Fuchu',
 'Fussa',
 'Gotenba-shi',
 'Inagi-shi',
 'Jōsō-shi',
 'Kamisu',
 'Kasukabe',
 'Katsuura',
 'Kawasaki',
 'Kumagaya',
 'Kōtō',
 'Machida',
 'Meguro',
 'Minato',
 'Mishima',
 'Musashino',
 'Narita',
 'Saitama-shi',
 'Shibayama-machi',
 'Shibuya',
 'Shiki',
 'Shinagawa',
 'Shinjuku',
 'Tachikawa-shi',
 'Tama',
 'Tokorozawa',
 'Tokyo',
 'Urayasu',
 'Utsunomiya',
 'Yokohama',
 'Ōta']

In [ ]:
data['location_region'].sort_values().unique().tolist()

['Chiba',
 'Gunma',
 'Ibaraki',
 'Kanagawa',
 'Saitama',
 'Shizuoka',
 'Tochigi',
 'Tokyo']

In [ ]:
brasil['location_locality'].sort_values().unique().tolist()

['Chiyoda',
 'Chuo',
 "Jin'nan",
 'Kawasaki',
 'Minato',
 'Narita',
 'Narita-shi',
 'Oota-ku',
 'Roppongi',
 'Shibuya',
 'Shinjuku',
 'Tachikawa-shi',
 'Taitō',
 'Tokyo',
 'Toshima',
 'Urayasu',
 'Yokohama',
 'Ōta']

In [ ]:
brasil['location_region'].sort_values().unique().tolist()

['Chiba', 'Kanagawa', 'Tokyo']

In [ ]:
brasil['location_locality'][brasil['location_locality']=='Narita-shi'] = 'Narita'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
brasil['location_locality'][brasil['location_locality']=='Narita-shi']

Series([], Name: location_locality, dtype: object)

In [ ]:
brasil['location_locality'][brasil['location_locality']=='Narita']

68    Narita
69    Narita
70    Narita
71    Narita
Name: location_locality, dtype: object

### Data

In [ ]:
data

,fsq_id,categories,distance,link,name,geocodes_main_latitude,geocodes_main_longitude,location_address,location_formatted_address,location_locality,location_postcode,location_region,popularity,rating,tastes,tips
0,517fcb2be4b0d7e32b2c9a68,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",932,/v3/places/517fcb2be4b0d7e32b2c9a68,Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,外神田1丁目2-12,"外神田1丁目2-12, 千代田区, Tokyo, 101-0021",Tokyo,101-0021,Tokyo,0.992807,9.2,"['hotel', 'cozy']","[{'created_at': '2019-04-24T07:37:54.000Z', 't..."
1,517089e9e4b0d21e986153c3,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",2776,/v3/places/517089e9e4b0d21e986153c3,The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,紀尾井町1-2,"紀尾井町1-2, 千代田区, Tokyo, 102-0094",Chiyoda,102-0094,Tokyo,0.997768,9.0,"['friendly staff', 'scenic views', 'hotel', 'b...","[{'created_at': '2019-03-03T02:13:09.000Z', 't..."
2,4f80f0bae4b0e160b9c9e122,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",2480,/v3/places/4f80f0bae4b0e160b9c9e122,Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧),35.712912,139.777796,上野7丁目2-16,"上野7丁目2-16, 台東区, Tokyo, 110-0005",Tokyo,110-0005,Tokyo,0.991224,8.7,"['saunas', 'open-air bath', 'cold-water bath']","[{'created_at': '2021-12-06T00:50:18.000Z', 't..."
3,598970be35f9830771f06b3f,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",3106,/v3/places/598970be35f9830771f06b3f,APA Hotel Asakusa Tawaramachi-Ekimae (アパホテル 浅草...,35.710112,139.790113,西浅草1丁目2-3,"西浅草1丁目2-3, 台東区, Tokyo, 111-0035",Tokyo,111-0035,Tokyo,0.993129,8.7,NaN,"[{'created_at': '2020-02-11T07:46:18.000Z', 't..."
4,5211312e11d259e1a2b3385a,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",1969,/v3/places/5211312e11d259e1a2b3385a,Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi...,35.679206,139.769727,八重洲2丁目2-7,"八重洲2丁目2-7, 中央区, Tokyo, 104-0028",Chuo,104-0028,Tokyo,0.988267,8.6,['bath houses'],"[{'created_at': '2016-09-06T15:24:42.000Z', 't..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,6021eac0dc86d61c512b9d92,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",31759,/v3/places/6021eac0dc86d61c512b9d92,LINK FOREST,35.619700,139.421640,鶴牧3丁目5-3,"鶴牧3丁目5-3, 多摩市, Tokyo, 206-0034",Tama,206-0034,Tokyo,0.992253,NaN,NaN,"[{'created_at': '2021-03-25T23:26:29.000Z', 't..."
91,513805a1e4b032c75badf416,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",34743,/v3/places/513805a1e4b032c75badf416,ホテルココアミルク,36.006641,139.788515,立野276-1,"立野276-1, 春日部市, Saitama, 344-0134",Kasukabe,344-0134,Saitama,0.983966,NaN,NaN,[]
92,4dd0e28452b1f8915bd0e895,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",41385,/v3/places/4dd0e28452b1f8915bd0e895,ホテルルートイン水海道駅前,36.017496,139.991883,水海道宝町1555-2,"水海道宝町1555-2 (水海道宝町), 常総市, Ibaraki, 303-0023",Jōsō-shi,303-0023,Ibaraki,0.991480,NaN,NaN,[]
93,4c5d77ad94fd0f470665cb45,"[{'id': 19014, 'name': 'Hotel', 'icon': {'pref...",65615,/v3/places/4c5d77ad94fd0f470665cb45,ホテルシティーフィールドかごはら,36.173067,139.331743,籠原南1-123,"籠原南1-123, 熊谷市, Saitama, 360-0847",Kumagaya,360-0847,Saitama,0.960615,NaN,NaN,"[{'created_at': '2019-06-01T13:30:49.000Z', 't..."
94,4ebb8e0577c8d9bd1b9358cb,"[{'id': 19010, 'name': 'Bed and Breakfast', 'i...",88024,/v3/places/4ebb8e0577c8d9bd1b9358cb,鈴嘉旅館,35.818861,140.724906,太田129-23,"太田129-23, 神栖市, Ibaraki, 314-0254",Kamisu,314-0254,Ibaraki,0.990899,NaN,NaN,[]

In [ ]:
brasil

,fsq_id,categories,distance,link,name,geocodes_main_latitude,geocodes_main_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,popularity,tips,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,tastes
0,505fce2be4b0a054473fa2eb,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",734.0,/v3/places/505fce2be4b0a054473fa2eb,SAUDADE,35.703322,139.765882,湯島2丁目3-14,JP,エムサ湯島 1F,"湯島2丁目3-14 (エムサ湯島 1F), 文京区, Tokyo",Tokyo,113-0034,Tokyo,0.672851,[],Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN
1,b91c2784f0b44e826bdfef64,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",372.0,/v3/places/b91c2784f0b44e826bdfef64,TUCANO'S GRILL and BAR,35.698788,139.774789,神田花岡町1-1,JP,NaN,"神田花岡町1-1, 千代田区, 東京都, 101-0028",Chiyoda,101-0028,Tokyo,NaN,[],Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN
2,40a90c773f0d4e7d9b05426c,"[{'id': 13031, 'name': 'Burger Joint', 'icon':...",383.0,/v3/places/40a90c773f0d4e7d9b05426c,トゥッカーノグリル&バー,35.699082,139.774807,神田花岡町1,JP,NaN,"神田花岡町1, 千代田区, 東京都, 101-0028",Chiyoda,101-0028,Tokyo,NaN,[],Anshin Oyado (安心お宿 秋葉原電気街店),35.697955,139.770792,NaN,NaN,NaN
3,56738a44498e84771b21395a,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",432.0,/v3/places/56738a44498e84771b21395a,Brasilica Grill Churrascaria (ブラジリカ グリル),35.675996,139.736733,赤坂3丁目10-4,JP,風月堂ビル 5F,"赤坂3丁目10-4 (風月堂ビル 5F), 港区, Tokyo, 107-0052",Tokyo,107-0052,Tokyo,0.829911,"[{'created_at': '2016-12-19T16:23:29.000Z', 't...",The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,NaN,7.6,NaN
4,e91ed07f7ad74c3ca56dfe6c,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",756.0,/v3/places/e91ed07f7ad74c3ca56dfe6c,La10Tokyo ラテントウキョウ,35.683879,139.730263,四谷2-2,JP,NaN,"四谷2-2, 新宿区, 東京都, 160-0004",Shinjuku,160-0004,Tokyo,NaN,[],The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東...,35.679886,139.737048,第22相信ビル 1F,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",219.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",Yokohama,221-0056,Kanagawa,NaN,[],Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口),35.467834,139.624715,横浜ベイクォーター 3F,NaN,NaN
94,5f0d3896938b7c3b5e5fa837,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",405.0,/v3/places/5f0d3896938b7c3b5e5fa837,Rio grande Grill,35.466548,139.622226,西区南幸1丁目1-1,JP,B3F ハマチカ内,"西区南幸1丁目1-1 (B3F ハマチカ内), 横浜市, Kanagawa, 220-0005",Yokohama,220-0005,Kanagawa,0.952048,"[{'created_at': '2021-10-02T11:09:12.000Z', 't...",カプセルプラス横浜,35.466405,139.617794,NaN,NaN,NaN
95,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",792.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",Yokohama,221-0056,Kanagawa,NaN,[],カプセルプラス横浜,35.466405,139.617794,横浜ベイクォーター 3F,NaN,NaN
96,535a620411d212a99bebe77b,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",696.0,/v3/places/535a620411d212a99bebe77b,RIO GRANDE GRILL 横浜ベイクォーター,35.466282,139.626928,神奈川区金港町1-10,JP,横浜ベイクォーター 3F,"神奈川区金港町1-10 (横浜ベイクォーター 3F), 横浜市, Kanagawa, 221...",Yokohama,221-0056,Kanagawa,0.954174,"[{'created_at': '2020-01-05T08:16:44.000Z', 't...",Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター3F エリア: 横浜駅,7.5,"['lunch', 'good for working', 'cozy', 'good fo..."
97,0cdac660a52e474cbae5cdbc,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",735.0,/v3/places/0cdac660a52e474cbae5cdbc,リオグランデグリル 横浜ベイクォーター,35.466538,139.626548,神奈川区金港町1-10,JP,NaN,"神奈川区金港町1-10, 横浜市, 神奈川県, 221-0056",Yokohama,221-0056,Kanagawa,NaN,[],Yokohama Tokyu Rei Hotel (横浜東急REIホテル),35.459946,139.625860,横浜ベイクォーター 3F,NaN,NaN

In [ ]:
data.info()

# rating -> 28 Nulos
# tastes -> 60 Nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   fsq_id                      95 non-null     object
 1   categories                  95 non-null     object
 2   distance                    95 non-null     int64
 3   link                        95 non-null     object
 4   name                        95 non-null     object
 5   geocodes_main_latitude      95 non-null     float64
 6   geocodes_main_longitude     95 non-null     float64
 7   location_address            95 non-null     object
 8   location_formatted_address  95 non-null     object
 9   location_locality           95 non-null     object
 10  location_postcode           95 non-null     object
 11  location_region             95 non-null     object
 12  popularity                  95 non-null     float64
 13  rating                      67 non-null     float64
 14  tastes                      35 non-null     object
 15  tips                        95 non-null     object
dtypes: float64(4), int64(1), object(11)
memory usage: 12.0+ KB

In [ ]:
brasil.isnull().sum()

# location_cross_street -> 51 Nulos
# popularity -> 40 Nulos
# location_address_extended -> 60 Nulos
# rating -> 82 Nulos
# tastes -> 85 Nulos

fsq_id                         0
categories                     0
distance                       0
link                           0
name                           0
geocodes_main_latitude         0
geocodes_main_longitude        0
location_address               0
location_country               0
location_cross_street         51
location_formatted_address     0
location_locality              0
location_postcode              0
location_region                0
popularity                    40
tips                           0
hotel                          0
hotel_latitude                 0
hotel_longitude                0
location_address_extended     60
rating                        82
tastes                        85
dtype: int64

In [ ]:
len(brasil.index)

98

In [ ]:
len(brasil.groupby(by='hotel'))

37

In [ ]:
brasil.groupby(by='hotel')['name'].count().sort_values(ascending=False)

hotel
APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上)                              16
THE BLOSSOM HIBIYA                                                         5
Sotetsu Fresa Inn Shimbashi-Hibiyaguchi (相鉄フレッサイン新橋日比谷口)                   5
Daiwa Roynet Hotel Yokohama-Kannai (ダイワロイネットホテル横浜関内)                       5
APA HOTEL Keisei Narita-Ekimae (アパホテル 京成成田駅前)                              4
Hotel New Green Okachimachi (ホテルニューグリーン御徒町)                                3
Super Hotel Premier Tokyo-eki Yaesu Chuo-guchi (スーパーホテルLohas東京駅八重洲中央口)     3
Sotetsu Fresa Inn (相鉄フレッサイン横浜駅東口)                                          3
Hotel New Otani (ホテルニューオータニ)                                               3
スカイスパYOKOHAMA                                                              3
Anshin Oyado (安心お宿 秋葉原電気街店)                                                3
Annex Tower (アネックスタワー)                                                     2
Via Inn Akihabara (ヴィアイン秋葉原)                                               2
Tokyo Inn (東京イン)                                                           2
The Tokyo Edition Toranomon (東京エディション虎ノ門)                                  2
The Prince Gallery Tokyo Kioicho (ザ・プリンスギャラリー東京紀尾井町)                       2
アパホテル 秋葉原駅北                                                                2
Akihabara Washington Hotel (秋葉原ワシントンホテル)                                   2
Keio Presso Inn Kanda (京王プレッソイン神田)                                         2
カプセル&サウナ 川崎ビッグ                                                             2
Comfort Hotel Tokyo Kanda (コンフォートホテル東京神田)                                  2
Sotetsu Fresa Inn (相鉄フレッサイン)                                               2
APA Hotel Kanda Eki Higashi (アパホテル神田駅東)                                    2
カプセルイン大塚                                                                   2
Rex Inn Kawasaki (レックスイン川崎)                                                2
Navios Yokohama (ナビオス横浜)                                                   2
Miyako City Tokyo Takanawa (都シティ 東京高輪)                                     2
カプセルプラス横浜                                                                  2
Korean YMCA Asia Youth Center in Japan (YMCAアジア青少年センター)                    2
Yokohama Tokyu Rei Hotel (横浜東急REIホテル)                                      2
Disney Ambassador Hotel (ディズニーアンバサダーホテル)                                   1
Toyoko Inn (東横イン 立川駅北口)                                                    1
The Okura Tokyo                                                            1
Spa Resort President (スパリゾート プレジデント)                                       1
Sauna & Capsule Hotel Hokuo (サウナ&カプセルホテル北欧)                                1
Mitsui Garden Hotel Gotanda (三井ガーデンホテル五反田)                                 1
Smile Hotel Tokyo Nihonbashi (スマイルホテル 東京日本橋)                               1
Name: name, dtype: int64

In [ ]:
brasil[brasil['hotel']=='APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上)']

,fsq_id,categories,distance,link,name,geocodes_main_latitude,geocodes_main_longitude,location_address,location_country,location_cross_street,location_formatted_address,location_locality,location_postcode,location_region,popularity,tips,hotel,hotel_latitude,hotel_longitude,location_address_extended,rating,tastes
40,528af03311d281c7eee110d4,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",724.0,/v3/places/528af03311d281c7eee110d4,"Barbacoa, Shibuya",35.661043,139.700333,宇田川町20-15,JP,ヒューマックスパビリオン渋谷公園通り 7F,"宇田川町20-15 (ヒューマックスパビリオン渋谷公園通り 7F), 渋谷区, Tokyo,...",Tokyo,150-0042,Tokyo,0.932480,"[{'created_at': '2018-11-09T03:23:58.000Z', 't...",APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,8.5,"['all you can eat', 'pineapple', 'churrasco', ..."
41,53c0fa87498e6127c41f69b1,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",395.0,/v3/places/53c0fa87498e6127c41f69b1,Gocchi Batta,35.658529,139.698268,道玄坂2丁目8-1,JP,大和田ビル 2F,"道玄坂2丁目8-1 (大和田ビル 2F), 渋谷区, Tokyo, 150-0043",Tokyo,150-0043,Tokyo,0.829161,"[{'created_at': '2020-12-16T00:50:04.000Z', 't...",APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,6.7,"['beer', 'all you can eat', 'churrasco']"
42,51d7129f498e518d75167223,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",299.0,/v3/places/51d7129f498e518d75167223,Bar blen blen blen,35.658404,139.697068,道玄坂1丁目17-12,JP,野々ビル 2F,"道玄坂1丁目17-12 (野々ビル 2F), 渋谷区, Tokyo, 150-0043",Tokyo,150-0043,Tokyo,0.782495,"[{'created_at': '2016-10-06T06:19:24.000Z', 't...",APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,NaN,NaN
43,5368d16e498e8e238500d054,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",358.0,/v3/places/5368d16e498e8e238500d054,ブラジリアン食堂 BANCHO 渋谷店,35.659251,139.696204,道玄坂2丁目19-13,JP,NaN,"道玄坂2丁目19-13, 渋谷区, Tokyo, 150-0043",Tokyo,150-0043,Tokyo,0.422566,"[{'created_at': '2014-05-13T12:30:01.000Z', 't...",APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,NaN,NaN
44,5b9a6f8ead910e002c2d47a1,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",436.0,/v3/places/5b9a6f8ead910e002c2d47a1,和牛シュラスコ&炙り肉寿司 Calluna 渋谷店,35.658145,139.699326,道玄坂1丁目5-5,JP,藤木ビル 3F,"道玄坂1丁目5-5 (藤木ビル 3F), 神南, Tokyo, 150-0043",Jin'nan,150-0043,Tokyo,0.049515,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,NaN,NaN
45,5ac87cac04d1ae058febbd21,"[{'id': 13003, 'name': 'Bar', 'icon': {'prefix...",437.0,/v3/places/5ac87cac04d1ae058febbd21,肉寿司・シュラスコ・シカゴピザ 肉バル カルーナ 渋谷店,35.658145,139.699326,道玄坂1丁目5-5,JP,藤木ビル３F,"道玄坂1丁目5-5 (藤木ビル３F), 渋谷区, Tokyo, 150-0043",Tokyo,150-0043,Tokyo,0.338346,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,NaN,NaN
46,5beea7082b274a002ccc96bc,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",483.0,/v3/places/5beea7082b274a002ccc96bc,肉バル シュラスコ 渋谷本店,35.660254,139.697262,道玄坂2丁目25-10,JP,ベニー清建ビル 7F,"道玄坂2丁目25-10 (ベニー清建ビル 7F), 渋谷区, Tokyo, 150-0043",Tokyo,150-0043,Tokyo,0.157230,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,ベニー清建ビル 7F,NaN,NaN
47,539b1659498ee5525ab6eac3,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",605.0,/v3/places/539b1659498ee5525ab6eac3,ブラジリアン酒場デビル 渋谷肉横丁店,35.661121,139.698477,宇田川町13-8,JP,ちとせ会館2F 渋谷肉横丁,"宇田川町13-8 (ちとせ会館2F 渋谷肉横丁), 渋谷区, Tokyo, 150-0042",Tokyo,150-0042,Tokyo,0.755056,"[{'created_at': '2017-08-23T14:10:38.000Z', 't...",APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,ちとせ会館2F 渋谷肉横丁,NaN,NaN
48,8c1c030fe8db4f5b6a601481,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",208.0,/v3/places/8c1c030fe8db4f5b6a601481,ブレン・ブレン・ブレン,35.657092,139.697088,道玄坂1丁目17-12,JP,NaN,"道玄坂1丁目17-12, 渋谷区, 東京都",Shibuya,150-0043,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,野々ビル2F,NaN,NaN
49,2691efd65ca7444f19a92ee0,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",414.0,/v3/places/2691efd65ca7444f19a92ee0,トゥッカーノ,35.659969,139.695822,道玄坂2丁目23-12,JP,NaN,"道玄坂2丁目23-12, 渋谷区, 東京都, 150-0043",Shibuya,150-0043,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,渋谷フォンティスビルB1,NaN,NaN
50,ff915e0ec4c84c8648d26e48,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",424.0,/v3/places/ff915e0ec4c84c8648d26e48,TUCANO'S,35.660048,139.695909,道玄坂2丁目23-12,JP,NaN,"道玄坂2丁目23-12, 渋谷区, 東京都, 150-0043",Shibuya,150-0043,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,渋谷フォンティスビルB1,NaN,NaN
51,2e0c7d1e80ac4e5af5542cb8,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",621.0,/v3/places/2e0c7d1e80ac4e5af5542cb8,DEVIL,35.661121,139.698477,宇田川町13-8,JP,NaN,"宇田川町13-8, 渋谷区, 東京都, 150-0042",Shibuya,150-0042,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,ちとせ会館 2F渋谷肉横丁,NaN,NaN
52,80a87675ad814375d1452b04,"[{'id': 13020, 'name': 'Sake Bar', 'icon': {'p...",630.0,/v3/places/80a87675ad814375d1452b04,デビルチキン,35.661154,139.698616,宇田川町13-8,JP,NaN,"宇田川町13-8, 渋谷区, 東京都, 150-0042",Shibuya,150-0042,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,ちとせ会館2F渋谷肉横丁,NaN,NaN
53,f5c84ef610c6433ce181aaac,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",632.0,/v3/places/f5c84ef610c6433ce181aaac,DEVIL 渋谷肉横丁店,35.661199,139.698564,宇田川町13-8,JP,NaN,"宇田川町13-8, 渋谷区, 東京都, 150-0042",Shibuya,150-0042,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,ちとせ会館 2F エリア: 渋谷,NaN,NaN
54,80c3b7b93aaf40559a6d208a,"[{'id': 13026, 'name': 'BBQ Joint', 'icon': {'...",716.0,/v3/places/80c3b7b93aaf40559a6d208a,Barbacoa Churrascaria Shibuya,35.661179,139.700177,宇田川町20-15,JP,NaN,"宇田川町20-15, 渋谷区, 東京都, 150-0042",Shibuya,150-0042,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,NaN,NaN,NaN
55,b2bb0a119d9744d8e6afd263,"[{'id': 13079, 'name': 'Brazilian Restaurant',...",792.0,/v3/places/b2bb0a119d9744d8e6afd263,東京タンゴシティ Milonga,35.662132,139.700056,神南1丁目20-16,JP,NaN,"神南1丁目20-16, 渋谷区, 東京都, 150-0041",Shibuya,150-0041,Tokyo,NaN,[],APA Hotel Shibuya Dogenzaka Ue (アパホテル渋谷道玄坂上),35.656304,139.694989,高山ランドビル6F,NaN,NaN